/**
 * Dependența de un obicei — 11 scored questions + the urgency question.
 *
 * GENERATED by `scripts/import-quizzes.mjs` from the client's
 * `Chestionare_Emmanuel_CliniX/chestionar_dependenta.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift.
 */
import type { ScoredQuiz } from "@/content/scored-quizzes";

export const ADICTII: ScoredQuiz = {
  "slug": "adictii",
  "route": "adictii",
  "seo": {
    "title": "Dependența de un obicei — test de auto-evaluare",
    "description": "Test de auto-evaluare pentru dependența de un obicei: 12 întrebări, o notă de la 1 la 10 și riscurile pe care le indică răspunsurile tale."
  },
  "hero": {
    "eyebrow": "Test de auto-evaluare · 12 întrebări",
    "title": "Dependența de un obicei",
    "subtitle": "Cât control mai ai, de fapt?",
    "lead": "Gândește-te la obiceiul care te preocupă cel mai mult — telefon, social media, jocuri, alcool, țigări, pariuri, cumpărături sau altceva — și răspunde cu el în minte, pe baza ultimelor trei luni. Cele 12 întrebări de mai jos îți dau o notă de la 1 la 10 și riscurile concrete pe care le indică răspunsurile tale.",
    "startButton": "Începe testul →"
  },
  "scoreLabel": "Nota ta",
  "questions": [
    {
      "text": "Cât de des petreci mai mult timp cu acest obicei decât ți-ai propus inițial?",
      "options": [
        {
          "label": "Niciodată — mă opresc când am decis",
          "score": 10
        },
        {
          "label": "Rar — ocazional mai întind puțin",
          "score": 7
        },
        {
          "label": "Deseori — „încă cinci minute\" devine o oră",
          "score": 4
        },
        {
          "label": "Aproape de fiecare dată — timpul dispare complet",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 70,
      "risk": {
        "title": "Pierderea controlului asupra duratei",
        "text": "Diferența dintre cât îți propui și cât faci efectiv e primul indicator obiectiv al pierderii controlului. Se lărgește treptat și, în majoritatea cazurilor, nu se restrânge singură."
      }
    },
    {
      "text": "Ai încercat să reduci sau să te oprești și nu ai reușit?",
      "options": [
        {
          "label": "Nu am simțit nevoia — dețin controlul",
          "score": 10
        },
        {
          "label": "Am redus ușor atunci când mi-am propus",
          "score": 7
        },
        {
          "label": "Am încercat de câteva ori — țin câteva zile, apoi revin",
          "score": 4
        },
        {
          "label": "Am încercat de multe ori și eșuez constant",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 85,
      "risk": {
        "title": "Încercări eșuate care lasă urme",
        "text": "Fiecare încercare nereușită întărește convingerea că nu se poate, iar convingerea reduce probabilitatea următoarei încercări. Nu e o problemă de voință — e motivul pentru care sprijinul extern schimbă rata de succes."
      }
    },
    {
      "text": "Cât de des te gândești la acest obicei când nu îl practici?",
      "options": [
        {
          "label": "Rar sau deloc",
          "score": 10
        },
        {
          "label": "Ocazional, în momente de plictiseală",
          "score": 7
        },
        {
          "label": "Deseori — gândul revine constant pe parcursul zilei",
          "score": 4
        },
        {
          "label": "Aproape permanent — mintea mea e mereu acolo",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 75,
      "risk": {
        "title": "Spațiu mental ocupat permanent",
        "text": "Când gândul revine constant, atenția disponibilă pentru orice altceva scade măsurabil. Este și semnul că sistemul de recompensă s-a reorganizat în jurul unui singur obiect."
      }
    },
    {
      "text": "Cât de des neglijezi responsabilități (muncă, familie, sănătate) din cauza acestui obicei?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar — s-a întâmplat izolat",
          "score": 7
        },
        {
          "label": "Deseori — amân sau ratez lucruri importante",
          "score": 4
        },
        {
          "label": "Constant — responsabilitățile au ajuns pe locul doi",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 92,
      "risk": {
        "title": "Consecințe care ies în exterior",
        "text": "Momentul în care obiceiul începe să coste lucruri din afara lui marchează trecerea de la obicei la problemă. De aici, pierderile se acumulează mai repede decât capacitatea de a le repara."
      }
    },
    {
      "text": "Cum te simți când nu poți practica obiceiul o perioadă?",
      "options": [
        {
          "label": "Normal — nici nu observ lipsa",
          "score": 10
        },
        {
          "label": "Un mic disconfort care trece repede",
          "score": 7
        },
        {
          "label": "Iritabil, neliniștit, cu dispoziție proastă",
          "score": 4
        },
        {
          "label": "Foarte rău — nervozitate intensă, anxietate, uneori simptome fizice",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 88,
      "risk": {
        "title": "Semne de dependență fiziologică",
        "text": "Disconfortul la întrerupere arată că organismul s-a adaptat la prezența obiceiului și îl tratează ca pe o normalitate. Din acest punct, oprirea bruscă și fără sprijin are o rată de eșec ridicată."
      }
    },
    {
      "text": "Ai observat că ai nevoie de tot mai mult (timp, cantitate, intensitate) pentru același efect?",
      "options": [
        {
          "label": "Nu — consumul meu e stabil de mult timp",
          "score": 10
        },
        {
          "label": "Ușor — a crescut puțin în timp",
          "score": 7
        },
        {
          "label": "Da, clar — ce îmi ajungea acum un an nu mă mai satisface",
          "score": 4
        },
        {
          "label": "Da, dramatic — escaladarea e vizibilă și mă îngrijorează",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 90,
      "risk": {
        "title": "Escaladare cu prag care urcă",
        "text": "Toleranța crește în trepte, iar fiecare treaptă devine noul minim. E mecanismul care face ca situația de peste un an să fie previzibil mai gravă decât cea de acum, în lipsa unei intervenții."
      }
    },
    {
      "text": "Cât de des folosești acest obicei ca să scapi de emoții neplăcute (stres, plictiseală, singurătate, tristețe)?",
      "options": [
        {
          "label": "Rar — îl practic din plăcere, nu din nevoie",
          "score": 10
        },
        {
          "label": "Uneori, după zile grele",
          "score": 7
        },
        {
          "label": "Deseori — e principalul meu mod de a face față stresului",
          "score": 4
        },
        {
          "label": "Aproape mereu — e singurul refugiu pe care îl am",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 82,
      "risk": {
        "title": "Singurul mecanism de reglare rămas",
        "text": "Când obiceiul devine principala cale de a gestiona emoțiile, celelalte metode se atrofiază din lipsă de folosire. Oprirea devine astfel mult mai greu de susținut: ar însemna să rămâi fără nicio soluție."
      }
    },
    {
      "text": "Cât de des ascunzi sau minimizezi acest obicei față de cei apropiați?",
      "options": [
        {
          "label": "Deloc — sunt complet transparent",
          "score": 10
        },
        {
          "label": "Rar — nu ascund, dar nici nu dau detalii",
          "score": 7
        },
        {
          "label": "Deseori — mint despre cât timp, câți bani sau cât consum",
          "score": 4
        },
        {
          "label": "Constant — nimeni din jur nu știe adevărata amploare",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 86,
      "risk": {
        "title": "Izolare construită în jurul obiceiului",
        "text": "Ascunderea taie exact legăturile care ar putea funcționa ca frână. Cu cât distanța dintre imaginea publică și realitate crește, cu atât devine mai greu să ceri ajutor fără să ai și o mărturisire de făcut."
      }
    },
    {
      "text": "Cât de mult afectează acest obicei somnul, sănătatea sau banii tăi?",
      "options": [
        {
          "label": "Deloc — nu are impact măsurabil",
          "score": 10
        },
        {
          "label": "Puțin — dorm ocazional mai târziu sau cheltui puțin peste plan",
          "score": 7
        },
        {
          "label": "Vizibil — somn sacrificat constant, sănătate neglijată sau cheltuieli care dor",
          "score": 4
        },
        {
          "label": "Serios — consecințele fizice sau financiare se acumulează",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 80,
      "risk": {
        "title": "Costuri care se acumulează tăcut",
        "text": "Consecințele fizice și financiare cresc lent și devin vizibile abia când ating un prag greu de ignorat. Până atunci, majoritatea oamenilor le tratează ca pe niște cheltuieli separate, fără legătură cu obiceiul."
      }
    },
    {
      "text": "Ți-au spus persoanele apropiate că sunt îngrijorate de acest obicei?",
      "options": [
        {
          "label": "Niciodată — nu e un subiect",
          "score": 10
        },
        {
          "label": "În glumă, ocazional",
          "score": 7
        },
        {
          "label": "Da, serios — cel puțin o persoană mi-a spus direct",
          "score": 4
        },
        {
          "label": "Da, repetat — mai mulți oameni au ridicat problema, iar asta creează conflicte",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 78,
      "risk": {
        "title": "Semnal din exterior, greu de văzut din interior",
        "text": "Cei din jur observă schimbarea înaintea persoanei în cauză, pentru că au termen de comparație. Când mai multe persoane ridică aceeași problemă, probabilitatea ca ele să se înșele toate este mică."
      }
    },
    {
      "text": "Dacă ești complet sincer: cât control mai ai, de fapt, asupra acestui obicei?",
      "options": [
        {
          "label": "Control total — eu decid când și cât",
          "score": 10
        },
        {
          "label": "Control bun — cu mici scăpări",
          "score": 7
        },
        {
          "label": "Control parțial — obiceiul câștigă mai des decât câștig eu",
          "score": 4
        },
        {
          "label": "Aproape deloc — simt că obiceiul mă controlează pe mine",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 95,
      "risk": {
        "title": "Raport de forțe deja înclinat",
        "text": "Recunoașterea pierderii controlului este, statistic, cel mai bun predictor al reușitei unei intervenții — și cel mai des amânat pas. Fără el, planurile de reducere se reiau la nesfârșit, cu aceleași rezultate."
      }
    }
  ],
  "urgency": {
    "text": "Cât de repede vrei să rezolvi asta?",
    "options": [
      {
        "label": "Acum, urgent",
        "urgency": "hot"
      },
      {
        "label": "În următoarele luni",
        "urgency": "warm"
      },
      {
        "label": "Doar mă documentez deocamdată",
        "urgency": "nurture"
      }
    ]
  },
  "combos": [
    {
      "q": [
        4,
        5
      ],
      "max": 4,
      "weight": 100,
      "risk": {
        "title": "Adaptare fiziologică deja instalată",
        "text": "Disconfortul la întrerupere și nevoia de tot mai mult sunt cele două semne care arată că organismul s-a adaptat. De aici, oprirea prin voință are o rată de eșec ridicată, iar riscul e ca fiecare eșec să adâncească tiparul."
      }
    },
    {
      "q": [
        10,
        1
      ],
      "max": 4,
      "weight": 98,
      "risk": {
        "title": "Control pierdut, cu încercări epuizate",
        "text": "Ai încercat de mai multe ori și simți deja că obiceiul câștigă. Este exact configurația în care intervenția externă schimbă cel mai mult rezultatul — și cea în care amânarea costă cel mai mult."
      }
    },
    {
      "q": [
        3,
        8
      ],
      "max": 4,
      "weight": 94,
      "risk": {
        "title": "Pierderi care ies din zona obiceiului",
        "text": "Responsabilitățile neglijate și costurile de sănătate sau financiare arată o problemă care s-a extins deja în viața reală. Aceste pierderi se acumulează mai repede decât capacitatea de a le repara."
      }
    },
    {
      "q": [
        7,
        9
      ],
      "max": 4,
      "weight": 88,
      "risk": {
        "title": "Izolare în jurul unui subiect",
        "text": "Ascunzi amploarea, iar cei din jur au ridicat deja problema. Distanța dintre cele două versiuni crește și taie exact legăturile care ar putea funcționa ca frână."
      }
    },
    {
      "q": [
        6,
        2
      ],
      "max": 4,
      "weight": 82,
      "risk": {
        "title": "Obicei devenit centru de reglare",
        "text": "Este principalul tău mod de a gestiona emoțiile, iar gândul revine constant. Celelalte mecanisme de reglare se atrofiază, iar oprirea ar însemna să rămâi, temporar, fără nicio soluție."
      }
    }
  ],
  "lead": {
    "title": "Aproape gata!",
    "text": "Completează datele de mai jos pentru a-ți vedea nota finală și analiza de risc.",
    "submit": "Vezi rezultatele mele →"
  },
  "result": {
    "risksHeading": "Ce riscuri indică răspunsurile tale",
    "risksSub": "Traiectoriile documentate cel mai frecvent la răspunsuri similare, în lipsa unei intervenții.",
    "closing": "<strong>De reținut:</strong> niciunul nu e un traseu obligatoriu și nimic din ce ai citit nu spune ceva despre tine ca om. Mecanismele descrise mai sus sunt fiziologice, se pot măsura, iar asta e și motivul pentru care se pot corecta.",
    "goodHeading": "Analiza răspunsurilor tale",
    "goodText": "Răspunsurile tale nu indică riscuri semnificative acum. Controlul asupra duratei, absența disconfortului la întrerupere și transparența față de cei din jur sunt exact cele trei elemente care cedează primele.",
    "bands": {
      "good": {
        "label": "Obicei sub control",
        "interp": "{name}, răspunsurile tale indică un obicei pe care îl controlezi, nu unul care te controlează."
      },
      "mid": {
        "label": "Semne de pierdere a controlului",
        "interp": "{name}, răspunsurile tale arată un obicei care a început să își construiască propriile mecanisme de întreținere."
      },
      "low": {
        "label": "Tipar de dependență — merită o evaluare",
        "interp": "{name}, răspunsurile tale indică un tipar care afectează deja mai multe zone ale vieții simultan."
      }
    }
  },
  "cta": {
    "lp": "/lp/adictii",
    "eyebrow": "Următorul pas",
    "hot": {
      "title": "Ai spus că vrei să rezolvi asta acum",
      "text": "Primul pas e o discuție de 15 minute, confidențială, în care îți spunem ce se poate măsura în cazul tău și ce opțiuni concrete există.",
      "button": "Vreau să rezolv problema"
    },
    "warm": {
      "title": "Care e următorul pas?",
      "text": "La Emmanuel Clinix măsurăm obiectiv modificările din sistemul de recompensă și îți arătăm ce se poate corecta. Primul pas e o discuție confidențială, nu o programare.",
      "button": "Vreau să văd ce se poate face"
    },
    "nurture": {
      "title": "Când vrei să înțelegi mai bine",
      "text": "Îți explicăm cum se evaluează obiectiv un tipar de dependență și ce arată rezultatele. Fără programare, fără obligații.",
      "button": "Află mai multe"
    }
  },
  "note": "Este un instrument de auto-evaluare online, cu rol informativ. Nu este un test medical și nu oferă un diagnostic.",
  "legal": "Acest chestionar este un instrument de auto-evaluare online, cu caracter exclusiv informativ și educațional. Nu este un test medical, nu reprezintă un diagnostic și nu înlocuiește consultul unui medic sau al unui psiholog. Nota și riscurile afișate sunt orientative, generate automat pe baza răspunsurilor pe care le-ați dat, și pot varia în funcție de mulți factori individuali. Riscurile descrise sunt tendințe generale întâlnite în literatura de specialitate, nu predicții despre situația dumneavoastră. Pentru orice problemă de sănătate, adresați-vă unui specialist. Emmanuel Clinix nu garantează rezultate specifice în urma completării acestui test."
};
