/**
 * Nivelul de anxietate — 10 scored questions + the urgency question.
 *
 * GENERATED by `scripts/import-quizzes.mjs` from the client's
 * `Chestionare_Emmanuel_CliniX/chestionar_anxietate.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift.
 */
import type { ScoredQuiz } from "@/content/scored-quizzes";

export const ANXIETATE: ScoredQuiz = {
  "slug": "anxietate",
  "route": "anxietate",
  "seo": {
    "title": "Nivelul de anxietate — test de auto-evaluare",
    "description": "Test de auto-evaluare a nivelului de anxietate: 11 întrebări, o notă de la 1 la 10 și riscurile pe care le indică răspunsurile tale."
  },
  "hero": {
    "eyebrow": "Test de auto-evaluare · 11 întrebări",
    "title": "Nivelul de anxietate",
    "subtitle": "Cât de mult te ține anxietatea în alertă?",
    "lead": "Răspunde sincer la cele 11 întrebări de mai jos, gândindu-te la ultimele două săptămâni. La final primești o notă de la 1 la 10 și riscurile concrete pe care le indică răspunsurile tale.",
    "startButton": "Începe testul →"
  },
  "scoreLabel": "Nota ta",
  "questions": [
    {
      "text": "Cât de des te-ai simțit nervos, anxios sau pe muchie în ultimele două săptămâni?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Câteva zile",
          "score": 7
        },
        {
          "label": "Mai mult de jumătate din zile",
          "score": 4
        },
        {
          "label": "Aproape în fiecare zi",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 70,
      "risk": {
        "title": "Anxietate trecută în regim continuu",
        "text": "Peste jumătate din zile înseamnă că starea nu mai e o reacție la ceva anume, ci fundalul permanent. Din acest punct creierul recalibrează pragul de alarmă în jos și reacționează la lucruri tot mai mici."
      }
    },
    {
      "text": "Cât de des nu reușești să oprești sau să controlezi îngrijorările?",
      "options": [
        {
          "label": "Niciodată — le pot pune deoparte",
          "score": 10
        },
        {
          "label": "Rar — cu efort, le opresc",
          "score": 7
        },
        {
          "label": "Deseori — se rostogolesc singure",
          "score": 4
        },
        {
          "label": "Aproape mereu — mintea nu se oprește deloc",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 78,
      "risk": {
        "title": "Îngrijorare care se autoîntreține",
        "text": "Fiecare scenariu negativ imaginat produce aceeași reacție fiziologică ca un pericol real și confirmă creierului că avea dreptate să se alarmeze. Fără intervenție, bucla se strânge și devine tot mai greu de întrerupt voluntar."
      }
    },
    {
      "text": "Cât de greu îți este să te relaxezi și să ieși din starea de alertă?",
      "options": [
        {
          "label": "Deloc greu — mă relaxez ușor",
          "score": 10
        },
        {
          "label": "Uneori am nevoie de mai mult timp",
          "score": 7
        },
        {
          "label": "Greu — rareori ajung cu adevărat relaxat",
          "score": 4
        },
        {
          "label": "Foarte greu — nu îmi amintesc când am fost relaxat ultima dată",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 72,
      "risk": {
        "title": "Prag de activare rămas ridicat",
        "text": "Când sistemul nu mai coboară din alertă, mușchii, respirația și pulsul rămân peste linia de bază permanent. Efectul apare în timp ca oboseală inexplicabilă și dureri fără cauză identificabilă."
      }
    },
    {
      "text": "Ai simptome fizice de anxietate (palpitații, transpirații, tremurături, respirație scurtă, senzație de nod în gât)?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Săptămânal",
          "score": 4
        },
        {
          "label": "Aproape zilnic",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 82,
      "risk": {
        "title": "Simptome fizice care devin ele însele declanșator",
        "text": "Odată apărute, senzațiile fizice sperie mai mult decât situația inițială și declanșează un nou val de anxietate. Așa se instalează atacurile de panică: nu din cauza vieții, ci din frica de propriul corp."
      }
    },
    {
      "text": "Cât de des eviți situații, locuri sau persoane din cauza anxietății?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar, în situații excepționale",
          "score": 7
        },
        {
          "label": "Deseori — refuz sau amân lucruri din cauza ei",
          "score": 4
        },
        {
          "label": "Constant — mi-am restrâns vizibil viața",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 88,
      "risk": {
        "title": "Restrângerea treptată a vieții",
        "text": "Fiecare evitare aduce ușurare imediată și învață creierul că locul evitat era într-adevăr periculos. Lista crește lună de lună, iar teritoriul în care te simți în siguranță se micșorează fără să observi."
      }
    },
    {
      "text": "Cât de des te simți atât de neliniștit încât îți vine greu să stai locului?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Aproape zilnic",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 55,
      "risk": {
        "title": "Neliniște motorie continuă",
        "text": "Corpul consumă energie pentru o descărcare care nu vine niciodată. Rezultatul e o oboseală profundă care nu se explică prin cât ai muncit efectiv."
      }
    },
    {
      "text": "Cum dormi când ești anxios?",
      "options": [
        {
          "label": "Normal — anxietatea nu îmi afectează somnul",
          "score": 10
        },
        {
          "label": "Adorm ceva mai greu",
          "score": 7
        },
        {
          "label": "Prost — adorm târziu sau mă trezesc cu gânduri",
          "score": 4
        },
        {
          "label": "Foarte prost — nopți în care mintea nu se oprește deloc",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 80,
      "risk": {
        "title": "Somn erodat de anxietate",
        "text": "Somnul insuficient scade a doua zi capacitatea creierului de a regla frica, deci anxietatea crește. Cercul se închide singur și, după câteva luni, funcționează independent de cauza inițială."
      }
    },
    {
      "text": "Cât de des te enervezi sau ești iritabil mai ușor decât de obicei?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori — cei din jur au observat",
          "score": 4
        },
        {
          "label": "Aproape zilnic — reacționez disproporționat",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 50,
      "risk": {
        "title": "Iritabilitate care afectează relațiile",
        "text": "Un sistem deja în alertă nu mai are rezervă pentru frustrări mici. Cei apropiați interpretează reacțiile ca respingere, iar sprijinul de care ai nevoie se subțiază exact când contează mai mult."
      }
    },
    {
      "text": "Cât de des îți afectează anxietatea munca, studiul sau relațiile?",
      "options": [
        {
          "label": "Deloc",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori — pierd oportunități sau amân decizii",
          "score": 4
        },
        {
          "label": "Constant — a schimbat vizibil cursul lucrurilor",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 85,
      "risk": {
        "title": "Costuri care se acumulează în afara ta",
        "text": "Anxietatea netratată nu rămâne o problemă interioară: produce decizii amânate, oportunități refuzate și relații tensionate. Sunt pierderi care se adună tăcut, iar recuperarea lor durează mult mai mult decât tratarea cauzei."
      }
    },
    {
      "text": "Cât de des simți că ceva rău urmează să se întâmple, fără un motiv clar?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Aproape permanent",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 68,
      "risk": {
        "title": "Alarmă fără obiect",
        "text": "Senzația de pericol iminent fără cauză identificabilă arată un sistem de alarmă care pornește singur. Netratată, se generalizează: tot mai multe contexte neutre ajung să declanșeze aceeași reacție."
      }
    }
  ],
  "urgency": {
    "text": "Cât de repede vrei să rezolvi asta?",
    "options": [
      {
        "label": "Acum, urgent",
        "urgency": "hot"
      },
      {
        "label": "În următoarele luni",
        "urgency": "warm"
      },
      {
        "label": "Doar mă documentez deocamdată",
        "urgency": "nurture"
      }
    ]
  },
  "combos": [
    {
      "q": [
        3,
        4
      ],
      "max": 4,
      "weight": 100,
      "risk": {
        "title": "Traiectorie tipică spre atacuri de panică",
        "text": "Simptome fizice frecvente, combinate cu evitarea situațiilor, sunt cei doi pași care preced cel mai des panica instalată. Fiecare evitare face următoarea expunere mai grea, iar cercul se strânge lună de lună."
      }
    },
    {
      "q": [
        1,
        6
      ],
      "max": 4,
      "weight": 96,
      "risk": {
        "title": "Îngrijorare care mănâncă somnul",
        "text": "Mintea care nu se oprește și somnul deteriorat se alimentează reciproc — noaptea slabă reduce a doua zi capacitatea creierului de a regla frica. După câteva luni, tiparul funcționează singur."
      }
    },
    {
      "q": [
        8,
        4
      ],
      "max": 4,
      "weight": 90,
      "risk": {
        "title": "Viață care se restrânge vizibil",
        "text": "Evitarea a început deja să producă pierderi concrete în muncă și în relații. E stadiul în care anxietatea nu mai e un disconfort interior, ci o forță care schimbă direcția lucrurilor."
      }
    },
    {
      "q": [
        0,
        2
      ],
      "max": 4,
      "weight": 84,
      "risk": {
        "title": "Alertă devenită fundal permanent",
        "text": "Anxietate în majoritatea zilelor, fără capacitatea de a reveni la relaxare, înseamnă un sistem care nu mai coboară niciodată. Corpul funcționează luni de zile peste linia de bază, cu costuri fiziologice reale."
      }
    },
    {
      "q": [
        7,
        9
      ],
      "max": 4,
      "weight": 76,
      "risk": {
        "title": "Sistem de alarmă care pornește singur",
        "text": "Senzația de pericol fără motiv, dublată de iritabilitate, arată un prag de alarmă coborât. Tot mai multe situații neutre ajung să fie citite ca amenințare."
      }
    }
  ],
  "lead": {
    "title": "Aproape gata!",
    "text": "Completează datele de mai jos pentru a-ți vedea nota finală și analiza de risc.",
    "submit": "Vezi rezultatele mele →"
  },
  "result": {
    "risksHeading": "Ce riscuri indică răspunsurile tale",
    "risksSub": "Traiectoriile documentate cel mai frecvent la răspunsuri similare, în lipsa unei intervenții.",
    "closing": "<strong>De reținut:</strong> niciunul nu e un traseu obligatoriu. Anxietatea răspunde, în general, bine la sprijin de specialitate — cu atât mai bine cu cât e abordată înainte ca evitarea să se extindă.",
    "goodHeading": "Analiza răspunsurilor tale",
    "goodText": "Răspunsurile tale nu indică riscuri semnificative acum. Reușești să te relaxezi, nu eviți situații și somnul rezistă — cele trei elemente care cedează primele când anxietatea începe să se instaleze.",
    "bands": {
      "good": {
        "label": "Nivel de anxietate scăzut",
        "interp": "{name}, răspunsurile tale indică un nivel de anxietate obișnuit, fără efecte asupra vieții de zi cu zi."
      },
      "mid": {
        "label": "Nivel moderat — tipar în formare",
        "interp": "{name}, răspunsurile tale arată o anxietate care a început să își construiască propriile mecanisme de întreținere."
      },
      "low": {
        "label": "Nivel ridicat — merită o evaluare",
        "interp": "{name}, răspunsurile tale indică o anxietate care afectează deja mai multe zone ale vieții simultan."
      }
    }
  },
  "cta": {
    "lp": "/lp/anxietate",
    "eyebrow": "Următorul pas",
    "hot": {
      "title": "Ai spus că vrei să rezolvi asta acum",
      "text": "Primul pas e o discuție de 15 minute, în care îți spunem ce se poate măsura în cazul tău și ce opțiuni concrete există.",
      "button": "Vreau să rezolv problema"
    },
    "warm": {
      "title": "Care e următorul pas?",
      "text": "La Emmanuel Clinix măsurăm obiectiv nivelul de activare al sistemului nervos și îți arătăm ce se poate corecta. Primul pas e o discuție, nu o programare.",
      "button": "Vreau să văd ce se poate face"
    },
    "nurture": {
      "title": "Când vrei să înțelegi mai bine",
      "text": "Îți explicăm cum se măsoară obiectiv anxietatea și ce arată rezultatele unei evaluări. Fără programare, fără obligații.",
      "button": "Află mai multe"
    }
  },
  "note": "Este un instrument de auto-evaluare online, cu rol informativ. Nu este un test medical și nu oferă un diagnostic.",
  "legal": "Acest chestionar este un instrument de auto-evaluare online, cu caracter exclusiv informativ și educațional. Nu este un test medical, nu reprezintă un diagnostic și nu înlocuiește consultul unui medic sau al unui psiholog. Nota și riscurile afișate sunt orientative, generate automat pe baza răspunsurilor pe care le-ați dat, și pot varia în funcție de mulți factori individuali. Riscurile descrise sunt tendințe generale întâlnite în literatura de specialitate, nu predicții despre situația dumneavoastră. Pentru orice problemă de sănătate, adresați-vă unui specialist. Emmanuel Clinix nu garantează rezultate specifice în urma completării acestui test."
};
