/**
 * Epuizarea profesională — 11 scored questions + the urgency question.
 *
 * GENERATED by `scripts/import-quizzes.mjs` from the client's
 * `Chestionare_Emmanuel_CliniX/chestionar_burnout.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift.
 */
import type { ScoredQuiz } from "@/content/scored-quizzes";

export const BURNOUT: ScoredQuiz = {
  "slug": "burnout",
  "route": "burnout",
  "seo": {
    "title": "Epuizarea profesională — test de auto-evaluare",
    "description": "Test de auto-evaluare a epuizării profesionale: 12 întrebări, o notă de la 1 la 10 și riscurile pe care le indică răspunsurile tale."
  },
  "hero": {
    "eyebrow": "Test de auto-evaluare · 12 întrebări",
    "title": "Epuizarea profesională",
    "subtitle": "Cât de aproape ești de limită?",
    "lead": "Răspunde sincer la cele 12 întrebări de mai jos, gândindu-te la ultimele luni. La final primești o notă de la 1 la 10 și riscurile concrete pe care le indică răspunsurile tale.",
    "startButton": "Începe testul →"
  },
  "scoreLabel": "Nota ta",
  "questions": [
    {
      "text": "Cât de des te simți epuizat emoțional la finalul unei zile de muncă?",
      "options": [
        {
          "label": "Niciodată — obosit, dar cu resurse",
          "score": 10
        },
        {
          "label": "Rar, doar în perioadele aglomerate",
          "score": 7
        },
        {
          "label": "Deseori — majoritatea zilelor mă golesc complet",
          "score": 4
        },
        {
          "label": "Aproape mereu — sunt stors încă de dimineață",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 78,
      "risk": {
        "title": "Epuizare care nu se mai reface peste noapte",
        "text": "Când golirea devine zilnică, deficitul se reportează de la o zi la alta în loc să se resetheze. Este primul dintre cele trei semne clasice ale epuizării profesionale și, de obicei, cel mai ignorat."
      }
    },
    {
      "text": "Te trezești dimineața deja obosit, cu senzația că nu poți face față unei noi zile?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar (de câteva ori pe lună)",
          "score": 7
        },
        {
          "label": "De câteva ori pe săptămână",
          "score": 4
        },
        {
          "label": "Aproape în fiecare dimineață",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 82,
      "risk": {
        "title": "Ziua începe din deficit",
        "text": "Oboseala prezentă înainte de a începe ceva arată că refacerea nocturnă nu mai funcționează. Din acest punct, orice zi normală de muncă devine un efort peste capacitate."
      }
    },
    {
      "text": "Cât de des te surprinzi că ai devenit cinic, detașat sau indiferent față de munca ta?",
      "options": [
        {
          "label": "Niciodată — îmi pasă la fel ca înainte",
          "score": 10
        },
        {
          "label": "Rar, în zilele foarte grele",
          "score": 7
        },
        {
          "label": "Deseori — simt că funcționez pe pilot automat",
          "score": 4
        },
        {
          "label": "Aproape mereu — nu îmi mai pasă și asta mă îngrijorează",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 88,
      "risk": {
        "title": "Detașare ca mecanism de protecție",
        "text": "Cinismul nu e o schimbare de caracter, ci felul în care mintea reduce consumul emoțional când nu mai are rezerve. Netratat, se extinde dincolo de muncă și afectează relațiile personale."
      }
    },
    {
      "text": "Cât de des ai senzația că, deși muncești mult, nu mai realizezi nimic important?",
      "options": [
        {
          "label": "Niciodată — văd clar rezultatele muncii mele",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori — muncesc mult, dar bat pasul pe loc",
          "score": 4
        },
        {
          "label": "Aproape mereu — mă simt ineficient indiferent cât efort depun",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 80,
      "risk": {
        "title": "Pierderea sentimentului de eficacitate",
        "text": "Al treilea semn clasic al epuizării: efortul rămâne mare, dar senzația de realizare dispare. Reacția obișnuită este să muncești și mai mult, ceea ce accelerează exact procesul care a produs problema."
      }
    },
    {
      "text": "Cât de des îți pierzi răbdarea din lucruri mărunte, la muncă sau acasă?",
      "options": [
        {
          "label": "Niciodată — am răbdarea obișnuită",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori — cei apropiați au început să observe",
          "score": 4
        },
        {
          "label": "Aproape zilnic — explodez din nimicuri și apoi regret",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 62,
      "risk": {
        "title": "Costuri care ajung acasă",
        "text": "Epuizarea profesională nu rămâne la birou: consumă rezerva de autocontrol disponibilă pentru toată ziua. Relațiile personale devin prima victimă colaterală și, de obicei, ultima observată."
      }
    },
    {
      "text": "Cât de greu îți este să te concentrezi și să duci sarcinile la capăt, comparativ cu acum un an?",
      "options": [
        {
          "label": "La fel de ușor ca înainte",
          "score": 10
        },
        {
          "label": "Puțin mai greu, în zilele obositoare",
          "score": 7
        },
        {
          "label": "Vizibil mai greu — ce îmi lua o oră îmi ia acum o jumătate de zi",
          "score": 4
        },
        {
          "label": "Mult mai greu — recitesc același paragraf de cinci ori",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 75,
      "risk": {
        "title": "Declin cognitiv măsurabil",
        "text": "Epuizarea prelungită afectează memoria de lucru și viteza de procesare, iar efectele sunt vizibile în teste obiective. Majoritatea oamenilor le pun pe seama vârstei sau a dezorganizării, nu pe cauza reală."
      }
    },
    {
      "text": "Ai simptome fizice recurente fără cauză medicală clară (dureri de cap, tensiune în umeri, probleme digestive, răceli dese)?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Săptămânal",
          "score": 4
        },
        {
          "label": "Aproape zilnic — corpul meu protestează constant",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 70,
      "risk": {
        "title": "Corpul a început să semnaleze",
        "text": "Simptomele fizice apar de obicei după luni de suprasolicitare și marchează implicarea sistemului imunitar și digestiv. Ignorate, stadiul următor nu e o agravare lentă, ci o oprire bruscă."
      }
    },
    {
      "text": "Cât de des lucrezi sau verifici mesajele de muncă seara, în weekend sau în concediu?",
      "options": [
        {
          "label": "Niciodată — când închid laptopul, am închis",
          "score": 10
        },
        {
          "label": "Rar, doar în situații excepționale",
          "score": 7
        },
        {
          "label": "Deseori — verific mailul și seara, și în weekend",
          "score": 4
        },
        {
          "label": "Constant — nu există „în afara programului\"",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 66,
      "risk": {
        "title": "Granițe dispărute complet",
        "text": "Fără o limită clară între muncă și restul vieții, creierul nu primește niciodată semnalul că poate opri. Ceea ce pare disponibilitate se traduce, în timp, în lipsa oricărei ferestre de refacere."
      }
    },
    {
      "text": "Cât de mult te ajută weekendul sau o zi liberă să te refaci?",
      "options": [
        {
          "label": "Complet — luni încep cu bateriile pline",
          "score": 10
        },
        {
          "label": "Destul de mult — mă refac în mare parte",
          "score": 7
        },
        {
          "label": "Puțin — luni dimineața sunt aproape la fel de obosit",
          "score": 4
        },
        {
          "label": "Deloc — nici după concediu nu mă simt refăcut",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 92,
      "risk": {
        "title": "Capacitate de refacere pierdută",
        "text": "Când odihna nu mai produce refacere, problema nu mai e cantitatea de muncă, ci mecanismul de recuperare în sine. E pragul de la care concediile, schimbarea jobului sau reducerea programului nu mai rezolvă nimic."
      }
    },
    {
      "text": "Cât de des mai simți plăcere în activitățile din afara muncii (hobby-uri, familie, prieteni)?",
      "options": [
        {
          "label": "Des — viața din afara muncii mă încarcă",
          "score": 10
        },
        {
          "label": "Destul de des, dar mai puțin ca înainte",
          "score": 7
        },
        {
          "label": "Rar — nu mai am energie pentru nimic după muncă",
          "score": 4
        },
        {
          "label": "Aproape deloc — munca a înghițit tot, restul e supraviețuire",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 85,
      "risk": {
        "title": "Viața redusă la muncă și recuperare",
        "text": "Pe măsură ce activitățile din afara muncii dispar, dispar și sursele care ar putea compensa consumul. Recuperarea devine tot mai lentă, iar munca rămâne singurul reper de valoare personală."
      }
    },
    {
      "text": "Cât de des te gândești serios să renunți la job sau la afacere, nu ca plan, ci ca să scapi?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar, în zilele foarte proaste",
          "score": 7
        },
        {
          "label": "Deseori — fantezia evadării apare săptămânal",
          "score": 4
        },
        {
          "label": "Zilnic — singurul lucru care mă ține e frica sau obligația",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 90,
      "risk": {
        "title": "Decizii luate ca să scapi, nu ca să câștigi",
        "text": "Fantezia evadării e un indicator de epuizare, nu un plan de carieră. Deciziile luate din această stare — demisii bruște, rupturi, abandonuri — sunt cel mai des regretate, pentru că problema se mută odată cu persoana."
      }
    }
  ],
  "urgency": {
    "text": "Cât de repede vrei să rezolvi asta?",
    "options": [
      {
        "label": "Acum, urgent",
        "urgency": "hot"
      },
      {
        "label": "În următoarele luni",
        "urgency": "warm"
      },
      {
        "label": "Doar mă documentez deocamdată",
        "urgency": "nurture"
      }
    ]
  },
  "combos": [
    {
      "q": [
        8,
        1
      ],
      "max": 4,
      "weight": 100,
      "risk": {
        "title": "Mecanismul de refacere nu mai funcționează",
        "text": "Te trezești deja obosit, iar zilele libere nu mai schimbă nimic. Este pragul de la care concediul, reducerea programului sau schimbarea jobului nu mai rezolvă problema — mecanismul de recuperare în sine e cel afectat."
      }
    },
    {
      "q": [
        2,
        10
      ],
      "max": 4,
      "weight": 98,
      "risk": {
        "title": "Epuizare avansată, cu ieșire căutată",
        "text": "Detașarea față de muncă, dublată de dorința zilnică de a scăpa, este tabloul clasic al fazei avansate. Deciziile luate din această stare sunt cel mai des regretate, pentru că problema nu rămâne în urmă."
      }
    },
    {
      "q": [
        0,
        3
      ],
      "max": 4,
      "weight": 92,
      "risk": {
        "title": "Efort mare, rezultat perceput zero",
        "text": "Golirea zilnică și senzația de ineficiență se alimentează reciproc. Reacția obișnuită — să muncești mai mult — accelerează exact procesul care a produs starea."
      }
    },
    {
      "q": [
        6,
        9
      ],
      "max": 4,
      "weight": 86,
      "risk": {
        "title": "Corpul semnalează, iar viața s-a restrâns",
        "text": "Simptomele fizice au apărut, iar activitățile din afara muncii au dispărut. Fără surse de refacere, semnalele corpului tind să se transforme într-o oprire bruscă, nu într-o agravare lentă."
      }
    },
    {
      "q": [
        5,
        7
      ],
      "max": 4,
      "weight": 78,
      "risk": {
        "title": "Cogniție în declin, fără granițe",
        "text": "Concentrarea a scăzut vizibil față de acum un an, iar munca nu se mai oprește niciodată. Creierul nu primește nicio fereastră de consolidare, iar declinul continuă atâta timp cât granițele lipsesc."
      }
    }
  ],
  "lead": {
    "title": "Aproape gata!",
    "text": "Completează datele de mai jos pentru a-ți vedea nota finală și analiza de risc.",
    "submit": "Vezi rezultatele mele →"
  },
  "result": {
    "risksHeading": "Ce riscuri indică răspunsurile tale",
    "risksSub": "Traiectoriile documentate cel mai frecvent la răspunsuri similare, în lipsa unei intervenții.",
    "closing": "<strong>De reținut:</strong> niciunul nu e un traseu obligatoriu. Epuizarea profesională produce modificări care se pot măsura obiectiv — iar când se vede exact ce s-a schimbat, se poate și corecta.",
    "goodHeading": "Analiza răspunsurilor tale",
    "goodText": "Răspunsurile tale nu indică riscuri semnificative acum. Te refaci în zilele libere, îți pasă de ce faci și ai viață în afara muncii — cele trei elemente care cedează primele.",
    "bands": {
      "good": {
        "label": "Fără semne de epuizare",
        "interp": "{name}, răspunsurile tale indică o relație cu munca în care consumul și refacerea sunt încă echilibrate."
      },
      "mid": {
        "label": "Epuizare în formare",
        "interp": "{name}, răspunsurile tale arată o acumulare care a depășit deja capacitatea normală de refacere."
      },
      "low": {
        "label": "Epuizare avansată — merită o evaluare",
        "interp": "{name}, răspunsurile tale indică o epuizare instalată, care afectează deja mai multe zone simultan."
      }
    }
  },
  "cta": {
    "lp": "/lp/burnout",
    "eyebrow": "Următorul pas",
    "hot": {
      "title": "Ai spus că vrei să rezolvi asta acum",
      "text": "Primul pas e o discuție de 15 minute, în care îți spunem ce se poate măsura în cazul tău și ce se poate corecta concret.",
      "button": "Vreau să rezolv problema"
    },
    "warm": {
      "title": "Care e următorul pas?",
      "text": "La Emmanuel Clinix măsurăm obiectiv modificările produse de epuizarea prelungită și îți arătăm ce se poate corecta. Primul pas e o discuție, nu o programare.",
      "button": "Vreau să văd ce se poate face"
    },
    "nurture": {
      "title": "Când vrei să înțelegi mai bine",
      "text": "Îți explicăm cum se măsoară obiectiv epuizarea și ce arată rezultatele unei evaluări. Fără programare, fără obligații.",
      "button": "Află mai multe"
    }
  },
  "note": "Este un instrument de auto-evaluare online, cu rol informativ. Nu este un test medical și nu oferă un diagnostic.",
  "legal": "Acest chestionar este un instrument de auto-evaluare online, cu caracter exclusiv informativ și educațional. Nu este un test medical, nu reprezintă un diagnostic și nu înlocuiește consultul unui medic sau al unui psiholog. Nota și riscurile afișate sunt orientative, generate automat pe baza răspunsurilor pe care le-ați dat, și pot varia în funcție de mulți factori individuali. Riscurile descrise sunt tendințe generale întâlnite în literatura de specialitate, nu predicții despre situația dumneavoastră. Pentru orice problemă de sănătate, adresați-vă unui specialist. Emmanuel Clinix nu garantează rezultate specifice în urma completării acestui test."
};
