/**
 * Starea de spirit și energia — 10 scored questions + the urgency question.
 *
 * GENERATED by `scripts/import-quizzes.mjs` from the client's
 * `Chestionare_Emmanuel_CliniX/chestionar_dispozitie.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift.
 */
import type { ScoredQuiz } from "@/content/scored-quizzes";

export const DISPOZITIE: ScoredQuiz = {
  "slug": "dispozitie",
  "route": "dispozitie",
  "seo": {
    "title": "Starea de spirit și energia — test de auto-evaluare",
    "description": "Test de auto-evaluare a stării de spirit și a energiei: 11 întrebări, o notă de la 1 la 10 și riscurile pe care le indică răspunsurile tale."
  },
  "hero": {
    "eyebrow": "Test de auto-evaluare · 11 întrebări",
    "title": "Starea de spirit și energia",
    "subtitle": "Cât de mult te-au schimbat ultimele săptămâni?",
    "lead": "Răspunde sincer la cele 11 întrebări de mai jos, gândindu-te la ultimele două săptămâni. La final primești o notă de la 1 la 10 și o analiză a ce indică răspunsurile tale.",
    "startButton": "Începe testul →"
  },
  "scoreLabel": "Nota ta",
  "questions": [
    {
      "text": "Cât de des ai pierdut interesul sau plăcerea pentru lucruri care în mod normal îți fac bine?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Câteva zile",
          "score": 7
        },
        {
          "label": "Mai mult de jumătate din zile",
          "score": 4
        },
        {
          "label": "Aproape în fiecare zi",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 88,
      "risk": {
        "title": "Pierderea capacității de a simți plăcere",
        "text": "Când plăcerea dispare, dispare și motivul de a face lucrurile care ar ajuta — deci activitatea scade, iar starea coboară mai mult. Este cel mai bine documentat mecanism prin care o perioadă grea devine una lungă."
      }
    },
    {
      "text": "Cât de des te-ai simțit trist, gol sau fără speranță?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Câteva zile",
          "score": 7
        },
        {
          "label": "Mai mult de jumătate din zile",
          "score": 4
        },
        {
          "label": "Aproape în fiecare zi",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 90,
      "risk": {
        "title": "Stare care s-a mutat din reacție în fundal",
        "text": "Peste jumătate din zile înseamnă că starea nu mai depinde de ce se întâmplă în jur. Din acest punct rareori se corectează prin schimbări de context — vacanță, job nou, mutare — pentru că nu contextul o mai întreține."
      }
    },
    {
      "text": "Cât de des te-ai simțit obosit sau fără energie, chiar și după ce te-ai odihnit?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Aproape zilnic",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 70,
      "risk": {
        "title": "Oboseală care nu răspunde la odihnă",
        "text": "Oboseala care persistă după somn nu e o problemă de odihnă, ci de reglare. Majoritatea oamenilor o interpretează ca lene sau lipsă de voință și își adaugă vinovăție peste o stare care are cauze fiziologice."
      }
    },
    {
      "text": "Cum a fost apetitul tău în ultimele două săptămâni?",
      "options": [
        {
          "label": "Normal",
          "score": 10
        },
        {
          "label": "Ușor schimbat",
          "score": 7
        },
        {
          "label": "Vizibil schimbat — mănânc mult mai puțin sau mult mai mult",
          "score": 4
        },
        {
          "label": "Complet dereglat, cu efect asupra greutății",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 55,
      "risk": {
        "title": "Dereglare a mecanismelor de bază",
        "text": "Apetitul e reglat de aceleași circuite care reglează dispoziția și somnul. Când se modifică vizibil, arată că dereglarea a trecut de nivelul emoțional și a ajuns la funcțiile de bază ale organismului."
      }
    },
    {
      "text": "Cât de des ai simțit că ai eșuat sau că i-ai dezamăgit pe cei din jur?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Aproape zilnic",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 85,
      "risk": {
        "title": "Autocritică devenită automată",
        "text": "Gândurile de acest tip nu descriu realitatea, ci reflectă starea în care sunt produse — dar sunt trăite ca adevăruri obiective. Cu cât se repetă mai mult, cu atât devin mai greu de pus la îndoială fără ajutor din afară."
      }
    },
    {
      "text": "Cât de greu îți este să te concentrezi (la muncă, la citit, într-o conversație)?",
      "options": [
        {
          "label": "Deloc greu",
          "score": 10
        },
        {
          "label": "Puțin mai greu ca de obicei",
          "score": 7
        },
        {
          "label": "Vizibil mai greu",
          "score": 4
        },
        {
          "label": "Foarte greu — recitesc același lucru de mai multe ori",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 60,
      "risk": {
        "title": "Costuri vizibile în muncă",
        "text": "Dificultatea de concentrare produce rezultate mai slabe, iar rezultatele slabe confirmă sentimentul de eșec. Este bucla prin care starea interioară începe să producă dovezi reale în favoarea ei."
      }
    },
    {
      "text": "Cât de des te-ai simțit izolat sau singur, chiar și când erai înconjurat de oameni?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Aproape mereu",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 80,
      "risk": {
        "title": "Retragere care se accelerează",
        "text": "Starea scade dorința de a fi cu oameni, iar lipsa oamenilor coboară starea mai mult. Este cercul care se închide cel mai repede și cel mai greu de rupt din interior."
      }
    },
    {
      "text": "Cât de greu îți este să te dai jos din pat dimineața, din lipsă de motivație?",
      "options": [
        {
          "label": "Deloc greu",
          "score": 10
        },
        {
          "label": "Uneori greu",
          "score": 7
        },
        {
          "label": "Deseori foarte greu",
          "score": 4
        },
        {
          "label": "Aproape imposibil — amân cât pot de mult",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 75,
      "risk": {
        "title": "Ziua începe deja în deficit",
        "text": "Când dimineața devine un obstacol, tot restul zilei pornește din urmă. Efortul consumat pentru lucruri elementare nu mai rămâne disponibil pentru nimic altceva."
      }
    },
    {
      "text": "Cât de mult te mai bucuri de lucrurile care înainte îți plăceau?",
      "options": [
        {
          "label": "La fel de mult ca înainte",
          "score": 10
        },
        {
          "label": "Puțin mai puțin",
          "score": 7
        },
        {
          "label": "Mult mai puțin",
          "score": 4
        },
        {
          "label": "Deloc — le fac mecanic sau le-am abandonat",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 82,
      "risk": {
        "title": "Restrângerea vieții la strictul necesar",
        "text": "Pe măsură ce activitățile plăcute dispar, dispar și sursele naturale prin care creierul își reglează dispoziția. Recuperarea devine mai lentă cu fiecare lună în care lista rămâne goală."
      }
    },
    {
      "text": "Cât de mult îți afectează aceste stări viața de zi cu zi (relații, muncă, treburi obișnuite)?",
      "options": [
        {
          "label": "Deloc",
          "score": 10
        },
        {
          "label": "Puțin",
          "score": 7
        },
        {
          "label": "Moderat — se vede în mai multe zone",
          "score": 4
        },
        {
          "label": "Major — abia mai fac față",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 92,
      "risk": {
        "title": "Efecte care ies din zona emoțională",
        "text": "Când starea afectează deja funcționarea zilnică, nu mai e o perioadă grea, ci o problemă care se autoîntreține. Statistic, cu cât trece mai mult timp până la evaluare, cu atât durează mai mult recuperarea."
      }
    }
  ],
  "urgency": {
    "text": "Cât de repede vrei să rezolvi asta?",
    "options": [
      {
        "label": "Acum, urgent",
        "urgency": "hot"
      },
      {
        "label": "În următoarele luni",
        "urgency": "warm"
      },
      {
        "label": "Doar mă documentez deocamdată",
        "urgency": "nurture"
      }
    ]
  },
  "combos": [
    {
      "q": [
        0,
        8
      ],
      "max": 4,
      "weight": 100,
      "risk": {
        "title": "Sursele naturale de reglare s-au închis",
        "text": "Plăcerea a dispărut, iar activitățile care o produceau au fost abandonate. Fără ele, creierul rămâne fără mecanismele proprii de revenire, iar starea se autoîntreține independent de circumstanțe."
      }
    },
    {
      "q": [
        1,
        9
      ],
      "max": 4,
      "weight": 98,
      "risk": {
        "title": "Stare instalată, cu efecte asupra funcționării",
        "text": "Starea persistă în majoritatea zilelor și afectează deja viața de zi cu zi. Este pragul de la care perioadele grele se transformă, în majoritatea cazurilor, în ceva care nu mai trece de la sine."
      }
    },
    {
      "q": [
        4,
        6
      ],
      "max": 4,
      "weight": 92,
      "risk": {
        "title": "Autocritică peste izolare",
        "text": "Sentimentul de eșec, combinat cu retragerea din jur, elimină exact corectivul care ar putea contrazice gândurile. Fără o perspectivă din afară, ele se consolidează ca adevăruri."
      }
    },
    {
      "q": [
        2,
        7
      ],
      "max": 4,
      "weight": 84,
      "risk": {
        "title": "Energie insuficientă pentru lucrurile de bază",
        "text": "Oboseala care nu trece și dimineața ca obstacol arată un deficit care nu se acoperă prin odihnă. E momentul în care majoritatea oamenilor își adaugă vinovăție peste o problemă fiziologică."
      }
    },
    {
      "q": [
        3,
        5
      ],
      "max": 4,
      "weight": 72,
      "risk": {
        "title": "Dereglare care a ajuns la funcțiile de bază",
        "text": "Apetitul modificat și concentrarea scăzută arată că dereglarea nu mai e doar emoțională. Sunt semne obiective, măsurabile — și tocmai de aceea abordabile."
      }
    }
  ],
  "lead": {
    "title": "Aproape gata!",
    "text": "Completează datele de mai jos pentru a-ți vedea nota finală și analiza de risc.",
    "submit": "Vezi rezultatele mele →"
  },
  "result": {
    "risksHeading": "Ce riscuri indică răspunsurile tale",
    "risksSub": "Traiectoriile documentate cel mai frecvent la răspunsuri similare, în lipsa unei intervenții.",
    "closing": "<strong>De reținut:</strong> niciunul nu e un traseu obligatoriu, iar nimic din ce ai citit mai sus nu spune ceva despre tine ca om. Stările de acest tip răspund bine la intervenție, iar cu cât e mai devreme, cu atât mai repede.",
    "goodHeading": "Analiza răspunsurilor tale",
    "goodText": "Răspunsurile tale nu indică riscuri semnificative acum. Plăcerea, energia și legătura cu oamenii din jur funcționează — cele trei elemente care cedează primele într-o perioadă grea.",
    "bands": {
      "good": {
        "label": "Dispoziție și energie echilibrate",
        "interp": "{name}, răspunsurile tale indică o stare de spirit stabilă, cu resurse disponibile."
      },
      "mid": {
        "label": "Semne de scădere — merită atenție",
        "interp": "{name}, răspunsurile tale arată o scădere a dispoziției și a energiei care a început să se mențină singură."
      },
      "low": {
        "label": "Merită discutat cu un specialist",
        "interp": "{name}, răspunsurile tale indică o stare care afectează deja mai multe zone ale vieții. Nu înseamnă un diagnostic — înseamnă că merită văzută de cineva calificat."
      }
    }
  },
  "cta": {
    "lp": "/lp/dispozitie",
    "eyebrow": "Următorul pas",
    "hot": {
      "title": "Ai spus că vrei să rezolvi asta acum",
      "text": "Primul pas e o discuție de 15 minute, în care îți spunem ce se poate măsura în cazul tău și ce opțiuni concrete există.",
      "button": "Vreau să rezolv problema"
    },
    "warm": {
      "title": "Care e următorul pas?",
      "text": "La Emmanuel Clinix măsurăm obiectiv ce se întâmplă la nivelul activității cerebrale și îți arătăm ce se poate corecta. Primul pas e o discuție, nu o programare.",
      "button": "Vreau să văd ce se poate face"
    },
    "nurture": {
      "title": "Când vrei să înțelegi mai bine",
      "text": "Îți explicăm cum se evaluează obiectiv dispoziția și energia și ce arată rezultatele. Fără programare, fără obligații.",
      "button": "Află mai multe"
    }
  },
  "note": "Este un instrument de auto-evaluare online, cu rol informativ. Nu este un test medical și nu oferă un diagnostic.",
  "legal": "Acest chestionar este un instrument de auto-evaluare online, cu caracter exclusiv informativ și educațional. Nu este un test medical, nu reprezintă un diagnostic și nu înlocuiește consultul unui medic sau al unui psiholog. Nota și riscurile afișate sunt orientative, generate automat pe baza răspunsurilor pe care le-ați dat, și pot varia în funcție de mulți factori individuali. Riscurile descrise sunt tendințe generale întâlnite în literatura de specialitate, nu predicții despre situația dumneavoastră. Pentru orice problemă de sănătate, adresați-vă unui specialist. Emmanuel Clinix nu garantează rezultate specifice în urma completării acestui test. Dacă treceți printr-o perioadă foarte grea și aveți gânduri de a vă face rău, sunați la 112 sau la TelVerde Antisuicid, 0800 801 200."
};
