/**
 * Focus și productivitate — 10 scored questions + the urgency question.
 *
 * GENERATED by `scripts/import-quizzes.mjs` from the client's
 * `Chestionare_Emmanuel_CliniX/chestionar_focus.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift.
 */
import type { ScoredQuiz } from "@/content/scored-quizzes";

export const FOCUS: ScoredQuiz = {
  "slug": "focus",
  "route": "focus",
  "seo": {
    "title": "Focus și productivitate — test de auto-evaluare",
    "description": "Test de auto-evaluare a concentrării și productivității: 11 întrebări, o notă de la 1 la 10 și riscurile pe care le indică răspunsurile tale."
  },
  "hero": {
    "eyebrow": "Test de auto-evaluare · 11 întrebări",
    "title": "Focus și productivitate",
    "subtitle": "Cât din capacitatea ta reală folosești, de fapt?",
    "lead": "Răspunde sincer la cele 11 întrebări de mai jos, gândindu-te la ultimele luni de lucru. La final primești o notă de la 1 la 10 și riscurile concrete pe care le indică răspunsurile tale.",
    "startButton": "Începe testul →"
  },
  "scoreLabel": "Nota ta",
  "questions": [
    {
      "text": "Cât timp poți lucra concentrat, fără întrerupere, la o singură sarcină importantă?",
      "options": [
        {
          "label": "Peste 60 de minute, fără efort",
          "score": 10
        },
        {
          "label": "30–60 de minute",
          "score": 7
        },
        {
          "label": "10–30 de minute — apoi mintea fuge",
          "score": 4
        },
        {
          "label": "Sub 10 minute — sar constant de la una la alta",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 75,
      "risk": {
        "title": "Capacitate de concentrare în scădere",
        "text": "Munca profundă are nevoie de aproximativ 20 de minute doar ca să pornească — sub acest prag nu ajungi niciodată la ea. Cu cât tiparul se repetă, cu atât creierul își pierde antrenamentul de a susține atenția."
      }
    },
    {
      "text": "Cât de des amâni sarcinile importante, deși știi exact ce ai de făcut?",
      "options": [
        {
          "label": "Niciodată — mă apuc direct de ce contează",
          "score": 10
        },
        {
          "label": "Rar, doar la sarcinile foarte neplăcute",
          "score": 7
        },
        {
          "label": "Deseori — încep ziua cu mărunțișuri și amân ce e greu",
          "score": 4
        },
        {
          "label": "Aproape mereu — lucrurile importante se împing săptămâni întregi",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 80,
      "risk": {
        "title": "Amânare care produce costuri reale",
        "text": "Amânarea nu e o problemă de disciplină, ci de reglare emoțională: creierul evită disconfortul, nu munca. Fiecare amânare crește anxietatea legată de sarcină, ceea ce face următoarea abordare și mai grea."
      }
    },
    {
      "text": "Cât de des îți verifici telefonul în timpul orelor de lucru?",
      "options": [
        {
          "label": "Rar — doar în pauze, intenționat",
          "score": 10
        },
        {
          "label": "O dată pe oră, scurt",
          "score": 7
        },
        {
          "label": "La fiecare 10–20 de minute",
          "score": 4
        },
        {
          "label": "Constant — mâna merge singură, de zeci de ori pe zi",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 65,
      "risk": {
        "title": "Atenție fragmentată permanent",
        "text": "După fiecare întrerupere, revenirea completă la sarcină durează în medie peste 20 de minute. La zeci de verificări pe zi, nu mai există niciun interval în care creierul să funcționeze la capacitate."
      }
    },
    {
      "text": "Cum îți este energia mentală pe parcursul zilei de lucru?",
      "options": [
        {
          "label": "Stabilă — funcționez bine de dimineața până seara",
          "score": 10
        },
        {
          "label": "Bună dimineața, cu un declin după-amiaza",
          "score": 7
        },
        {
          "label": "Instabilă — am 2–3 ore bune, restul zilei mă târăsc",
          "score": 4
        },
        {
          "label": "Constant scăzută — funcționez în ceață aproape toată ziua",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 70,
      "risk": {
        "title": "Ferestre productive tot mai scurte",
        "text": "Când doar câteva ore pe zi sunt utilizabile, restul timpului se consumă pe activități de umplutură care par muncă. Diferența dintre orele petrecute și rezultatele obținute crește lună de lună."
      }
    },
    {
      "text": "Câte dintre sarcinile pe care le începi le duci efectiv la capăt?",
      "options": [
        {
          "label": "Aproape toate — termin ce încep",
          "score": 10
        },
        {
          "label": "Majoritatea, cu mici întârzieri",
          "score": 7
        },
        {
          "label": "Cam jumătate — am multe proiecte abandonate",
          "score": 4
        },
        {
          "label": "Puține — încep cu entuziasm și abandonez pe drum",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 72,
      "risk": {
        "title": "Proiecte neterminate care se acumulează",
        "text": "Fiecare lucru început și abandonat rămâne activ în memoria de lucru și consumă resurse în fundal. Costul nu e doar proiectul pierdut, ci încrederea că data viitoare vei duce ceva la capăt."
      }
    },
    {
      "text": "Cât de clar îți este, la începutul zilei, care sunt cele mai importante 1–3 lucruri de făcut?",
      "options": [
        {
          "label": "Foarte clar — le știu dinainte și încep cu ele",
          "score": 10
        },
        {
          "label": "Destul de clar, dar le stabilesc din mers",
          "score": 7
        },
        {
          "label": "Vag — reacționez la ce apare (mailuri, mesaje, urgențe)",
          "score": 4
        },
        {
          "label": "Deloc — zilele mă trăiesc ele pe mine",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 68,
      "risk": {
        "title": "Zile conduse din exterior",
        "text": "Fără priorități stabilite dinainte, ziua se umple cu urgențele altora, care sunt mereu disponibile. Rezultatul e senzația de ocupat permanent, fără progres pe ce contează cu adevărat."
      }
    },
    {
      "text": "Cât de des lucrezi la mai multe lucruri deodată (taburi multiple, mail deschis, conversații în paralel)?",
      "options": [
        {
          "label": "Rar — lucrez secvențial, pe o singură sarcină",
          "score": 10
        },
        {
          "label": "Uneori, când e aglomerat",
          "score": 7
        },
        {
          "label": "Deseori — am mereu zece taburi și trei conversații active",
          "score": 4
        },
        {
          "label": "Permanent — nu îmi amintesc când am lucrat ultima dată la un singur lucru",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 60,
      "risk": {
        "title": "Comutare continuă care costă mai mult decât pare",
        "text": "Creierul nu lucrează în paralel, ci comută — iar fiecare comutare lasă în urmă atenție reziduală pe sarcina anterioară. Efectul e o zi întreagă petrecută la o fracțiune din capacitate."
      }
    },
    {
      "text": "Cum te simți la finalul unei zile obișnuite de lucru, raportat la ce ai realizat?",
      "options": [
        {
          "label": "Mulțumit — am produs ce mi-am propus",
          "score": 10
        },
        {
          "label": "OK — puteam mai mult, dar e rezonabil",
          "score": 7
        },
        {
          "label": "Frustrat — am fost ocupat toată ziua, dar n-am produs nimic important",
          "score": 4
        },
        {
          "label": "Vinovat și demoralizat — zilele trec și rezultatele nu apar",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 78,
      "risk": {
        "title": "Efort disociat de rezultat",
        "text": "Când efortul nu se mai traduce în rezultate, motivația scade, iar scăderea motivației produce zile și mai slabe. Este bucla prin care oamenii capabili ajung să se creadă incapabili."
      }
    },
    {
      "text": "Cât de mult îți afectează somnul, alimentația sau lipsa mișcării capacitatea de a munci?",
      "options": [
        {
          "label": "Deloc — stilul de viață îmi susține performanța",
          "score": 10
        },
        {
          "label": "Puțin — am derapaje, dar recuperez",
          "score": 7
        },
        {
          "label": "Vizibil — știu că trăiesc într-un mod care îmi sabotează munca",
          "score": 4
        },
        {
          "label": "Major — dorm prost, mănânc haotic, zero mișcare, și se vede în tot",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 74,
      "risk": {
        "title": "Fundament fiziologic erodat",
        "text": "Somnul, glicemia și mișcarea sunt infrastructura pe care rulează atenția — nicio metodă de productivitate nu compensează lipsa lor. Fără ele, efortul de a te organiza mai bine dă rezultate tot mai mici."
      }
    },
    {
      "text": "Cât de mare e diferența dintre ce știi că ai putea produce și ce produci efectiv?",
      "options": [
        {
          "label": "Mică — lucrez aproape de potențialul meu",
          "score": 10
        },
        {
          "label": "Moderată — mai am rezerve, dar progresez",
          "score": 7
        },
        {
          "label": "Mare — folosesc poate jumătate din capacitatea mea",
          "score": 4
        },
        {
          "label": "Uriașă — simt că îmi irosesc potențialul, și asta mă macină",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 85,
      "risk": {
        "title": "Diferență care începe să coste emoțional",
        "text": "Distanța dintre ce poți și ce faci nu rămâne o problemă de eficiență — devine, în timp, o sursă constantă de frustrare și autocritică. E momentul în care problema de productivitate trece în zona stării de spirit."
      }
    }
  ],
  "urgency": {
    "text": "Cât de repede vrei să rezolvi asta?",
    "options": [
      {
        "label": "Acum, urgent",
        "urgency": "hot"
      },
      {
        "label": "În următoarele luni",
        "urgency": "warm"
      },
      {
        "label": "Doar mă documentez deocamdată",
        "urgency": "nurture"
      }
    ]
  },
  "combos": [
    {
      "q": [
        1,
        7
      ],
      "max": 4,
      "weight": 100,
      "risk": {
        "title": "Buclă între amânare și demoralizare",
        "text": "Amâni ce contează, iar la finalul zilei rămâi cu senzația că nu ai produs nimic. Fiecare zi de acest tip face următoarea mai grea, iar tiparul se adâncește singur, indiferent de cât de multe metode încerci."
      }
    },
    {
      "q": [
        0,
        2
      ],
      "max": 4,
      "weight": 96,
      "risk": {
        "title": "Atenție fragmentată sub pragul util",
        "text": "Nu ajungi la munca profundă și te întrerupi la fiecare câteva minute. Sub 20 de minute neîntrerupte, creierul nu apucă niciodată să intre în starea în care produce cu adevărat."
      }
    },
    {
      "q": [
        8,
        3
      ],
      "max": 4,
      "weight": 90,
      "risk": {
        "title": "Fundament fiziologic care nu mai susține atenția",
        "text": "Energia mentală instabilă, pe fondul unui stil de viață care o sabotează, nu se corectează prin organizare. Este singura combinație din listă în care problema nu e la nivel de metodă, ci de biologie."
      }
    },
    {
      "q": [
        9,
        4
      ],
      "max": 4,
      "weight": 86,
      "risk": {
        "title": "Potențial nefolosit, cu cost emoțional",
        "text": "Proiectele abandonate și diferența resimțită între ce poți și ce faci se alimentează reciproc. În timp, problema iese din zona productivității și intră în cea a încrederii în sine."
      }
    },
    {
      "q": [
        5,
        6
      ],
      "max": 4,
      "weight": 78,
      "risk": {
        "title": "Zi condusă integral din exterior",
        "text": "Fără priorități clare și cu zece lucruri deschise simultan, ziua se umple cu urgențele altora. Rezultatul e ocupare permanentă fără progres, greu de recunoscut din interior."
      }
    }
  ],
  "lead": {
    "title": "Aproape gata!",
    "text": "Completează datele de mai jos pentru a-ți vedea nota finală și analiza de risc.",
    "submit": "Vezi rezultatele mele →"
  },
  "result": {
    "risksHeading": "Ce riscuri indică răspunsurile tale",
    "risksSub": "Traiectoriile documentate cel mai frecvent la răspunsuri similare, în lipsa unei intervenții.",
    "closing": "<strong>De reținut:</strong> niciunul nu e un traseu obligatoriu. Capacitatea de concentrare nu e o trăsătură de caracter — se poate măsura obiectiv, iar când se vede unde se rupe, se poate antrena.",
    "goodHeading": "Analiza răspunsurilor tale",
    "goodText": "Răspunsurile tale nu indică riscuri semnificative acum. Susții concentrarea, închizi ce începi și rezultatele urmează efortului — cele trei lucruri care se pierd primele.",
    "bands": {
      "good": {
        "label": "Focus solid",
        "interp": "{name}, răspunsurile tale indică o capacitate de concentrare care îți susține munca."
      },
      "mid": {
        "label": "Focus fragmentat — pierderi vizibile",
        "interp": "{name}, răspunsurile tale arată o atenție fragmentată, cu un decalaj tot mai mare între efort și rezultat."
      },
      "low": {
        "label": "Capacitate de concentrare sever afectată",
        "interp": "{name}, răspunsurile tale indică dificultăți de atenție care afectează deja mai multe zone simultan."
      }
    }
  },
  "cta": {
    "lp": "/lp/focus",
    "eyebrow": "Următorul pas",
    "hot": {
      "title": "Ai spus că vrei să rezolvi asta acum",
      "text": "Primul pas e o discuție de 15 minute, în care îți spunem ce se poate măsura în cazul tău și ce se poate antrena concret.",
      "button": "Vreau să rezolv problema"
    },
    "warm": {
      "title": "Care e următorul pas?",
      "text": "La Emmanuel Clinix măsurăm obiectiv tiparele de atenție din activitatea cerebrală și îți arătăm ce se poate antrena. Primul pas e o discuție, nu o programare.",
      "button": "Vreau să văd ce se poate face"
    },
    "nurture": {
      "title": "Când vrei să înțelegi mai bine",
      "text": "Îți explicăm cum se măsoară obiectiv atenția și ce arată rezultatele unei evaluări. Fără programare, fără obligații.",
      "button": "Află mai multe"
    }
  },
  "note": "Este un instrument de auto-evaluare online, cu rol informativ. Nu este un test medical și nu oferă un diagnostic.",
  "legal": "Acest chestionar este un instrument de auto-evaluare online, cu caracter exclusiv informativ și educațional. Nu este un test medical, nu reprezintă un diagnostic și nu înlocuiește consultul unui medic sau al unui psiholog. Nota și riscurile afișate sunt orientative, generate automat pe baza răspunsurilor pe care le-ați dat, și pot varia în funcție de mulți factori individuali. Riscurile descrise sunt tendințe generale întâlnite în literatura de specialitate, nu predicții despre situația dumneavoastră. Pentru orice problemă de sănătate, adresați-vă unui specialist. Emmanuel Clinix nu garantează rezultate specifice în urma completării acestui test."
};
