/**
 * Dureri de cap și migrene — 11 scored questions + the urgency question.
 *
 * GENERATED by `scripts/import-quizzes.mjs` from the client's
 * `Chestionare_Emmanuel_CliniX/chestionar_migrene.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift.
 */
import type { ScoredQuiz } from "@/content/scored-quizzes";

export const MIGRENE: ScoredQuiz = {
  "slug": "migrene",
  "route": "migrene",
  "seo": {
    "title": "Dureri de cap și migrene — test de auto-evaluare",
    "description": "Test de auto-evaluare pentru dureri de cap și migrene: 12 întrebări, o notă de la 1 la 10 și riscurile pe care le indică răspunsurile tale."
  },
  "hero": {
    "eyebrow": "Test de auto-evaluare · 12 întrebări",
    "title": "Dureri de cap și migrene",
    "subtitle": "Cât de mult îți iau, de fapt, din viață?",
    "lead": "Răspunde sincer la cele 12 întrebări de mai jos, gândindu-te la ultimele trei luni. La final primești o notă de la 1 la 10 și riscurile concrete pe care le indică răspunsurile tale.",
    "startButton": "Începe testul →"
  },
  "scoreLabel": "Nota ta",
  "questions": [
    {
      "text": "În câte zile pe lună ai dureri de cap, în medie?",
      "options": [
        {
          "label": "Sub o zi pe lună",
          "score": 10
        },
        {
          "label": "1–4 zile pe lună",
          "score": 7
        },
        {
          "label": "5–14 zile pe lună",
          "score": 4
        },
        {
          "label": "15 sau mai multe zile pe lună",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 92,
      "risk": {
        "title": "Prag de cronicizare atins sau apropiat",
        "text": "Peste 15 zile pe lună, durerea de cap intră în categoria cronică, iar mecanismul care o produce se schimbă: sistemul de durere devine el însuși sensibilizat. Din acest punct, tratarea episoadelor izolate dă rezultate tot mai slabe."
      }
    },
    {
      "text": "Cât de intensă este durerea când apare?",
      "options": [
        {
          "label": "Ușoară — o observ, dar îmi văd de treabă",
          "score": 10
        },
        {
          "label": "Moderată — mă deranjează, dar funcționez",
          "score": 7
        },
        {
          "label": "Puternică — îmi este greu să mă concentrez sau să continui",
          "score": 4
        },
        {
          "label": "Foarte puternică — trebuie să mă opresc din tot ce fac",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 70,
      "risk": {
        "title": "Episoade care întrerup complet activitatea",
        "text": "Durerea care obligă la oprire completă produce, în timp, un tipar de evitare: amâni, anulezi, refuzi. Costul se acumulează în afara episodului de durere, în lucrurile la care începi să nu mai contezi."
      }
    },
    {
      "text": "Cât durează, de obicei, un episod?",
      "options": [
        {
          "label": "Sub o oră",
          "score": 10
        },
        {
          "label": "1–4 ore",
          "score": 7
        },
        {
          "label": "4–24 de ore",
          "score": 4
        },
        {
          "label": "Peste o zi, uneori mai multe",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 66,
      "risk": {
        "title": "Episoade lungi, greu de întrerupt",
        "text": "Episoadele care depășesc 24 de ore răspund mai greu la orice intervenție luată târziu, pentru că mecanismul de durere a avut timp să se instaleze complet. Cu cât durata medie crește, cu atât recuperarea dintre episoade se scurtează."
      }
    },
    {
      "text": "Cât de des iei medicamente pentru durere de cap (inclusiv cele fără rețetă)?",
      "options": [
        {
          "label": "Rar sau deloc",
          "score": 10
        },
        {
          "label": "Câteva zile pe lună",
          "score": 7
        },
        {
          "label": "Peste 10 zile pe lună",
          "score": 4
        },
        {
          "label": "Aproape zilnic — nu pot funcționa fără",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 95,
      "risk": {
        "title": "Risc de cefalee provocată chiar de medicație",
        "text": "Analgezicele luate peste aproximativ 10–15 zile pe lună pot produce, în timp, exact durerea pe care încearcă să o oprească. Este una dintre cele mai frecvente cauze ale trecerii spre dureri aproape zilnice, și una dintre cele mai rar recunoscute."
      }
    },
    {
      "text": "Durerea e însoțită de greață, sensibilitate la lumină, la sunet sau de tulburări de vedere?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Aproape la fiecare episod",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 74,
      "risk": {
        "title": "Tablou care necesită evaluare de specialitate",
        "text": "Simptomele asociate schimbă natura problemei: nu mai e o simplă durere, ci un episod care implică mai multe sisteme simultan. Abordarea potrivită diferă semnificativ, motiv pentru care tratamentul generic dă rezultate slabe."
      }
    },
    {
      "text": "Câte zile din ultima lună ai fost nevoit să reduci activitatea, să anulezi planuri sau să lipsești de la muncă din cauza durerilor?",
      "options": [
        {
          "label": "Niciuna",
          "score": 10
        },
        {
          "label": "1–2 zile",
          "score": 7
        },
        {
          "label": "3–5 zile",
          "score": 4
        },
        {
          "label": "Peste 5 zile",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 88,
      "risk": {
        "title": "Pierderi care se acumulează lunar",
        "text": "Peste cinci zile pe lună înseamnă mai mult de două luni pierdute într-un an. Impactul apare în evaluări profesionale, în relații și în lucrurile pe care încetezi să le mai planifici, nu doar în zilele cu durere."
      }
    },
    {
      "text": "Cum e legătura dintre durerile de cap și somnul tău?",
      "options": [
        {
          "label": "Nu există legătură — dorm bine",
          "score": 10
        },
        {
          "label": "Ocazional apar după nopți proaste",
          "score": 7
        },
        {
          "label": "Clară — nopțile proaste aduc aproape sigur durere de cap",
          "score": 4
        },
        {
          "label": "Dublă — dorm prost din cauza durerii și mă doare capul din cauza somnului prost",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 80,
      "risk": {
        "title": "Cerc între somn și durere",
        "text": "Somnul insuficient scade pragul la care durerea se declanșează, iar durerea strică somnul următor. Este unul dintre puținele mecanisme din listă care, corectat, reduce simultan frecvența și intensitatea episoadelor."
      }
    },
    {
      "text": "Ai tensiune constantă în gât, umeri sau maxilar (inclusiv scrâșnit sau încleștare a dinților)?",
      "options": [
        {
          "label": "Deloc",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Permanent — le simt încordate aproape tot timpul",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 68,
      "risk": {
        "title": "Tensiune musculară care întreține durerea",
        "text": "Contractura menținută în zona cervicală și a maxilarului este un declanșator frecvent, activ inclusiv în somn. Fiind inconștientă, rareori e identificată drept cauză, iar durerea e tratată la nesfârșit ca și cum ar apărea din senin."
      }
    },
    {
      "text": "Cât de des apar durerile în perioade de stres sau imediat după ele?",
      "options": [
        {
          "label": "Nu există legătură",
          "score": 10
        },
        {
          "label": "Uneori",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Aproape întotdeauna — stresul e declanșatorul meu principal",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 64,
      "risk": {
        "title": "Declanșator care nu dispare singur",
        "text": "Când stresul e principalul declanșator, frecvența durerilor urmează încărcarea din viață, nu un tipar propriu. Fără o intervenție asupra mecanismului de bază, perioadele aglomerate vor produce previzibil episoade, an după an."
      }
    },
    {
      "text": "Cum au evoluat durerile în ultimul an?",
      "options": [
        {
          "label": "S-au rărit sau au dispărut",
          "score": 10
        },
        {
          "label": "Sunt cam la fel",
          "score": 7
        },
        {
          "label": "S-au înmulțit sau s-au intensificat vizibil",
          "score": 4
        },
        {
          "label": "S-au agravat mult — sunt mult mai dese decât acum un an",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 90,
      "risk": {
        "title": "Tendință de agravare deja instalată",
        "text": "O frecvență în creștere de la an la an arată un proces activ, nu o variație întâmplătoare. În lipsa unei evaluări, direcția obișnuită este spre episoade mai dese și mai greu de oprit, nu spre stabilizare."
      }
    },
    {
      "text": "Cât de des te gândești, în avans, că ar putea să te apuce durerea?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori — îmi planific lucrurile ținând cont de asta",
          "score": 4
        },
        {
          "label": "Aproape permanent — teama de următorul episod e mereu prezentă",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 82,
      "risk": {
        "title": "Viață organizată în jurul următorului episod",
        "text": "Anticiparea constantă menține sistemul nervos într-o stare de alertă care coboară chiar pragul de declanșare a durerii. Așa se ajunge ca teama de episod să contribuie la producerea lui."
      }
    }
  ],
  "urgency": {
    "text": "Cât de repede vrei să rezolvi asta?",
    "options": [
      {
        "label": "Acum, urgent",
        "urgency": "hot"
      },
      {
        "label": "În următoarele luni",
        "urgency": "warm"
      },
      {
        "label": "Doar mă documentez deocamdată",
        "urgency": "nurture"
      }
    ]
  },
  "combos": [
    {
      "q": [
        0,
        3
      ],
      "max": 4,
      "weight": 100,
      "risk": {
        "title": "Tipar de cefalee întreținută de medicație",
        "text": "Dureri frecvente combinate cu analgezice luate peste zece zile pe lună este configurația clasică în care medicația începe să întrețină problema. Este și una dintre puținele situații în care starea se înrăutățește tocmai pentru că e tratată greșit."
      }
    },
    {
      "q": [
        9,
        10
      ],
      "max": 4,
      "weight": 96,
      "risk": {
        "title": "Agravare, cu viața organizată în jurul ei",
        "text": "Durerile s-au înmulțit față de anul trecut, iar teama de următorul episod e permanentă. Alerta continuă coboară pragul de declanșare, ceea ce accelerează exact tendința pe care ai observat-o deja."
      }
    },
    {
      "q": [
        1,
        5
      ],
      "max": 4,
      "weight": 92,
      "risk": {
        "title": "Dizabilitate reală, măsurabilă în zile",
        "text": "Episoade care te opresc complet, plus zile pierdute lunar, înseamnă timp scos din viață și din muncă. La ritmul acesta, pierderea anuală depășește de obicei ce estimează majoritatea oamenilor."
      }
    },
    {
      "q": [
        6,
        7
      ],
      "max": 4,
      "weight": 88,
      "risk": {
        "title": "Doi factori întreținători, ambii corectabili",
        "text": "Somnul deteriorat și tensiunea musculară cervicală sunt cei mai frecvenți întreținători ai durerilor recurente. Sunt și zona în care o evaluare obiectivă schimbă cel mai repede frecvența episoadelor."
      }
    },
    {
      "q": [
        2,
        4
      ],
      "max": 4,
      "weight": 84,
      "risk": {
        "title": "Profil care necesită abordare specifică",
        "text": "Episoade lungi, însoțite de greață sau sensibilitate la lumină și sunet, descriu un tablou diferit de o durere de cap obișnuită. Tratat generic, răspunde slab — motiv pentru care mulți oameni concluzionează, greșit, că la ei nu funcționează nimic."
      }
    },
    {
      "q": [
        8,
        5
      ],
      "max": 4,
      "weight": 78,
      "risk": {
        "title": "Încărcare care se traduce direct în zile pierdute",
        "text": "Stresul îți declanșează episoadele, iar ele îți iau deja zile din lună. Fără o intervenție asupra mecanismului, fiecare perioadă aglomerată din următorii ani va produce previzibil aceleași pierderi."
      }
    }
  ],
  "lead": {
    "title": "Aproape gata!",
    "text": "Completează datele de mai jos pentru a-ți vedea nota finală și analiza de risc.",
    "submit": "Vezi rezultatele mele →"
  },
  "result": {
    "risksHeading": "Ce riscuri indică răspunsurile tale",
    "risksSub": "Traiectoriile documentate cel mai frecvent la răspunsuri similare, în lipsa unei intervenții.",
    "closing": "<strong>De reținut:</strong> niciunul nu e un traseu obligatoriu. Durerile de cap recurente au, în majoritatea cazurilor, mecanisme identificabile — iar când se vede care sunt, se poate acționa asupra lor, nu doar asupra episodului.",
    "goodHeading": "Analiza răspunsurilor tale",
    "goodText": "Răspunsurile tale nu indică riscuri semnificative acum. Frecvența e mică, nu depinzi de analgezice și durerile nu îți iau zile din lună — cele trei lucruri care se schimbă primele când problema începe să se instaleze.",
    "bands": {
      "good": {
        "label": "Dureri de cap ocazionale",
        "interp": "{name}, răspunsurile tale indică dureri de cap ocazionale, fără efecte semnificative asupra vieții de zi cu zi."
      },
      "mid": {
        "label": "Tipar recurent — merită urmărit",
        "interp": "{name}, răspunsurile tale arată dureri care au început să formeze un tipar și să își construiască propriii factori de întreținere."
      },
      "low": {
        "label": "Tipar frecvent — merită o evaluare",
        "interp": "{name}, răspunsurile tale indică dureri de cap frecvente, care afectează deja mai multe zone ale vieții simultan."
      }
    }
  },
  "cta": {
    "lp": "/lp/migrene",
    "eyebrow": "Următorul pas",
    "hot": {
      "title": "Ai spus că vrei să rezolvi asta acum",
      "text": "Primul pas e o discuție de 15 minute, în care îți spunem ce se poate măsura în cazul tău și ce factori se pot corecta concret.",
      "button": "Vreau să rezolv problema"
    },
    "warm": {
      "title": "Care e următorul pas?",
      "text": "La Emmanuel Clinix măsurăm obiectiv tiparele de activitate cerebrală implicate în durerile de cap recurente și îți arătăm ce se poate corecta. Primul pas e o discuție, nu o programare.",
      "button": "Vreau să văd ce se poate face"
    },
    "nurture": {
      "title": "Când vrei să înțelegi mai bine",
      "text": "Îți explicăm ce se poate măsura obiectiv în cazul durerilor de cap recurente și ce arată rezultatele unei evaluări. Fără programare, fără obligații.",
      "button": "Află mai multe"
    }
  },
  "note": "Este un instrument de auto-evaluare online, cu rol informativ. Nu este un test medical și nu oferă un diagnostic.",
  "legal": "Acest chestionar este un instrument de auto-evaluare online, cu caracter exclusiv informativ și educațional. Nu este un test medical, nu reprezintă un diagnostic și nu înlocuiește consultul unui medic sau al unui psiholog. Nota și riscurile afișate sunt orientative, generate automat pe baza răspunsurilor pe care le-ați dat, și pot varia în funcție de mulți factori individuali. Riscurile descrise sunt tendințe generale întâlnite în literatura de specialitate, nu predicții despre situația dumneavoastră. Pentru orice problemă de sănătate, adresați-vă unui specialist. Emmanuel Clinix nu garantează rezultate specifice în urma completării acestui test. Durerea de cap apărută brusc și neobișnuit de intensă, cea însoțită de febră, de rigiditate a cefei, de tulburări de vedere, de vorbire, de echilibru sau de forță musculară, precum și cea apărută după o lovitură la cap, necesită evaluare medicală de urgență: sunați la 112."
};
