/**
 * Atacurile de panică — 12 scored questions + the urgency question.
 *
 * GENERATED by `scripts/import-quizzes.mjs` from the client's
 * `Chestionare_Emmanuel_CliniX/chestionar_panica.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift.
 */
import type { ScoredQuiz } from "@/content/scored-quizzes";

export const PANICA: ScoredQuiz = {
  "slug": "panica",
  "route": "panica",
  "seo": {
    "title": "Atacurile de panică — test de auto-evaluare",
    "description": "Test de auto-evaluare pentru atacuri de panică: 13 întrebări, o notă de la 1 la 10 și riscurile pe care le indică răspunsurile tale."
  },
  "hero": {
    "eyebrow": "Test de auto-evaluare · 13 întrebări",
    "title": "Atacurile de panică",
    "subtitle": "Cât de mult îți dictează, de fapt, programul?",
    "lead": "Răspunde sincer la cele 13 întrebări de mai jos, gândindu-te la ultimele trei luni. La final primești o notă de la 1 la 10 și riscurile concrete pe care le indică răspunsurile tale.",
    "startButton": "Începe testul →"
  },
  "scoreLabel": "Nota ta",
  "questions": [
    {
      "text": "Cât de des ai avut, în ultimele trei luni, episoade de frică sau disconfort intens care apar brusc?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Unul sau două, în situații foarte stresante",
          "score": 7
        },
        {
          "label": "De câteva ori pe lună",
          "score": 4
        },
        {
          "label": "Săptămânal sau mai des",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 88,
      "risk": {
        "title": "Episoade care s-au transformat într-un tipar",
        "text": "Când episoadele se repetă săptămânal, creierul nu le mai tratează ca accidente, ci ca pe o amenințare de așteptat. Începe să scaneze permanent după semnele următorului, ceea ce îi face apariția mai probabilă, nu mai puțin."
      }
    },
    {
      "text": "Cât de repede ajunge episodul la intensitate maximă?",
      "options": [
        {
          "label": "Nu e cazul",
          "score": 10
        },
        {
          "label": "Treptat, în peste 20 de minute",
          "score": 7
        },
        {
          "label": "În aproximativ 10 minute",
          "score": 4
        },
        {
          "label": "În câteva minute sau mai puțin — mă lovește pe nepusă masă",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 66,
      "risk": {
        "title": "Debut brusc, imposibil de anticipat",
        "text": "Instalarea în câteva minute lasă senzația că nu există nimic de făcut, ceea ce alimentează neputința între episoade. Tocmai imprevizibilitatea, nu durerea în sine, e cea care restrânge cel mai mult viața oamenilor."
      }
    },
    {
      "text": "Ce simptome fizice apar în timpul episodului (palpitații, senzație de sufocare, amețeală, transpirații, furnicături, tremurat)?",
      "options": [
        {
          "label": "Niciunul",
          "score": 10
        },
        {
          "label": "Unul-două, ușoare",
          "score": 7
        },
        {
          "label": "Mai multe, clar resimțite",
          "score": 4
        },
        {
          "label": "Multe și intense — simt că îmi pierd controlul asupra corpului",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 74,
      "risk": {
        "title": "Corpul devine el însuși sursa fricii",
        "text": "Odată ce senzațiile fizice au speriat o dată, creierul începe să le monitorizeze și le detectează la intensități tot mai mici. Așa ajung o palpitație obișnuită sau o amețeală banală să declanșeze un episod complet."
      }
    },
    {
      "text": "În timpul episodului, te temi că se întâmplă ceva grav (că faci infarct, că leșini, că îți pierzi mințile, că mori)?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Aproape de fiecare dată",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 82,
      "risk": {
        "title": "Interpretare catastrofică devenită automată",
        "text": "Frica de consecință amplifică reacția fiziologică, iar reacția confirmă frica — asta transformă un val de anxietate într-un episod complet. Este mecanismul central al panicii și, tocmai de aceea, cel asupra căruia se poate interveni."
      }
    },
    {
      "text": "Între episoade, cât de des te gândești că ar putea urma altul?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori — mă preocupă des",
          "score": 4
        },
        {
          "label": "Aproape permanent — teama de următorul episod nu mă părăsește",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 92,
      "risk": {
        "title": "Frica de frică, prezentă tot timpul",
        "text": "Teama constantă de următorul episod menține sistemul nervos în alertă și coboară chiar pragul la care el se declanșează. Din acest punct, problema nu mai sunt cele câteva minute de panică, ci orele dintre ele."
      }
    },
    {
      "text": "Eviți locuri sau situații de teamă că ai putea avea un episod acolo (transport, magazine, cozi, locuri aglomerate, condus, să rămâi singur)?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar, în situații excepționale",
          "score": 7
        },
        {
          "label": "Deseori — am câteva locuri pe care le ocolesc",
          "score": 4
        },
        {
          "label": "Constant — lista de locuri evitate crește, iar viața mi s-a restrâns vizibil",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 95,
      "risk": {
        "title": "Restrângerea progresivă a teritoriului",
        "text": "Fiecare evitare aduce ușurare imediată și confirmă creierului că locul era într-adevăr periculos. Lista se lungește lună de lună, iar în lipsa unei intervenții acesta este traseul obișnuit către a nu mai ieși deloc din casă."
      }
    },
    {
      "text": "Ai gesturi care te fac să te simți mai în siguranță (să ieși doar însoțit, să stai lângă ieșire, să ai mereu apă sau o pastilă la tine, să verifici unde e cel mai apropiat spital)?",
      "options": [
        {
          "label": "Niciunul",
          "score": 10
        },
        {
          "label": "Unul-două, fără importanță",
          "score": 7
        },
        {
          "label": "Da, mai multe — le respect destul de strict",
          "score": 4
        },
        {
          "label": "Da, multe — fără ele nu ies din casă",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 78,
      "risk": {
        "title": "Siguranță împrumutată din obiecte și reguli",
        "text": "Aceste gesturi reduc anxietatea pe moment, dar îl învață pe creier că fără ele situația chiar ar fi periculoasă. Cu timpul, lista devine obligatorie, iar libertatea de mișcare depinde de respectarea ei."
      }
    },
    {
      "text": "Ai avut episoade care te-au trezit din somn?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "O dată",
          "score": 7
        },
        {
          "label": "De câteva ori",
          "score": 4
        },
        {
          "label": "Deseori — mi-e teamă să adorm",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 84,
      "risk": {
        "title": "Episoade nocturne care afectează somnul",
        "text": "Episoadele care apar în somn elimină ultimul loc perceput ca sigur și duc frecvent la amânarea orei de culcare. Privarea de somn care urmează coboară și mai mult pragul de declanșare, închizând cercul."
      }
    },
    {
      "text": "Ai ajuns la urgențe sau ai făcut investigații medicale din cauza acestor simptome?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "O dată — și rezultatele au fost bune",
          "score": 7
        },
        {
          "label": "De câteva ori",
          "score": 4
        },
        {
          "label": "De mai multe ori — deși rezultatele sunt bune, tot nu sunt liniștit",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 70,
      "risk": {
        "title": "Ciclu de verificări care nu liniștește",
        "text": "Rezultatele bune calmează pentru scurt timp, apoi îndoiala revine și cere o nouă confirmare. Fiecare investigație normală face următorul episod la fel de convingător, pentru că mecanismul real rămâne neatins."
      }
    },
    {
      "text": "Folosești alcool, calmante sau alte substanțe ca să previi sau să oprești episoadele?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar, în situații excepționale",
          "score": 7
        },
        {
          "label": "Deseori — mă bazez pe ele când știu că urmează o situație grea",
          "score": 4
        },
        {
          "label": "Aproape zilnic — nu mai fac față fără",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 86,
      "risk": {
        "title": "Dependență care se construiește peste panică",
        "text": "Substanțele reduc episodul pe moment și cresc anxietatea de fond între episoade, ceea ce impune doze tot mai mari. Panica netratată este una dintre cele mai frecvente căi de intrare în dependența de calmante."
      }
    },
    {
      "text": "Cât de mult îți afectează aceste episoade munca, studiul sau relațiile?",
      "options": [
        {
          "label": "Deloc",
          "score": 10
        },
        {
          "label": "Puțin",
          "score": 7
        },
        {
          "label": "Moderat — refuz sau amân lucruri din cauza lor",
          "score": 4
        },
        {
          "label": "Major — au schimbat vizibil cursul lucrurilor",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 90,
      "risk": {
        "title": "Costuri care ies din zona episodului",
        "text": "Panica netratată nu rămâne o problemă de câteva minute: produce oportunități refuzate, deplasări evitate și relații tensionate. Aceste pierderi se recuperează mult mai greu decât se tratează cauza care le-a produs."
      }
    },
    {
      "text": "Cum au evoluat episoadele în ultimele luni?",
      "options": [
        {
          "label": "S-au rărit sau au dispărut",
          "score": 10
        },
        {
          "label": "Sunt cam la fel",
          "score": 7
        },
        {
          "label": "S-au înmulțit sau s-au intensificat",
          "score": 4
        },
        {
          "label": "S-au agravat clar — sunt mult mai dese decât la început",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 93,
      "risk": {
        "title": "Tendință de agravare deja instalată",
        "text": "O frecvență în creștere arată un mecanism activ, care se autoîntreține, nu o variație întâmplătoare. Fără evaluare, direcția obișnuită este spre episoade mai dese și spre o listă tot mai lungă de situații evitate."
      }
    }
  ],
  "urgency": {
    "text": "Cât de repede vrei să rezolvi asta?",
    "options": [
      {
        "label": "Acum, urgent",
        "urgency": "hot"
      },
      {
        "label": "În următoarele luni",
        "urgency": "warm"
      },
      {
        "label": "Doar mă documentez deocamdată",
        "urgency": "nurture"
      }
    ]
  },
  "combos": [
    {
      "q": [
        4,
        5
      ],
      "max": 4,
      "weight": 100,
      "risk": {
        "title": "Traseu clasic spre restrângerea vieții",
        "text": "Teama permanentă de următorul episod, combinată cu evitarea locurilor, este combinația care transformă panica dintr-o problemă de câteva minute într-una care îți dictează programul. Fiecare lună în plus adaugă situații pe listă, iar recuperarea lor devine mai lentă."
      }
    },
    {
      "q": [
        11,
        0
      ],
      "max": 4,
      "weight": 97,
      "risk": {
        "title": "Episoade frecvente, în creștere",
        "text": "Apar deja des și s-au înmulțit față de început. E stadiul în care mecanismul se autoîntreține și în care intervenția are cel mai bun raport între efort și rezultat."
      }
    },
    {
      "q": [
        3,
        8
      ],
      "max": 4,
      "weight": 92,
      "risk": {
        "title": "Cerc de verificări medicale fără capăt",
        "text": "Convingerea că se întâmplă ceva grav, dublată de investigații repetate cu rezultate bune, arată un mecanism care nu se rezolvă prin analize. Liniștea durează până la episodul următor, pentru că sursa reală rămâne neatinsă."
      }
    },
    {
      "q": [
        9,
        6
      ],
      "max": 4,
      "weight": 88,
      "risk": {
        "title": "Funcționare condiționată de calmante și reguli",
        "text": "Substanțele și gesturile de siguranță reduc anxietatea pe moment și o cresc între episoade. Este drumul obișnuit prin care panica netratată se transformă, în plus, într-o dependență."
      }
    },
    {
      "q": [
        7,
        2
      ],
      "max": 4,
      "weight": 84,
      "risk": {
        "title": "Nici somnul nu mai e loc sigur",
        "text": "Episoadele nocturne, însoțite de simptome fizice intense, elimină ultimul context perceput ca sigur. Somnul amânat scade pragul de declanșare, iar episoadele devin previzibil mai frecvente."
      }
    },
    {
      "q": [
        10,
        1
      ],
      "max": 4,
      "weight": 80,
      "risk": {
        "title": "Imprevizibil, cu efecte în viața reală",
        "text": "Episoadele te lovesc fără avertisment și au început deja să schimbe lucruri în muncă sau în relații. Tocmai imprevizibilitatea e cea care produce cele mai multe renunțări, nu intensitatea în sine."
      }
    }
  ],
  "lead": {
    "title": "Aproape gata!",
    "text": "Completează datele de mai jos pentru a-ți vedea nota finală și analiza de risc.",
    "submit": "Vezi rezultatele mele →"
  },
  "result": {
    "risksHeading": "Ce riscuri indică răspunsurile tale",
    "risksSub": "Traiectoriile documentate cel mai frecvent la răspunsuri similare, în lipsa unei intervenții.",
    "closing": "<strong>De reținut:</strong> niciunul nu e un traseu obligatoriu. Panica are un mecanism bine descris și predictibil — iar asta e și motivul pentru care e una dintre stările în care sprijinul de specialitate schimbă lucrurile cel mai clar.",
    "goodHeading": "Analiza răspunsurilor tale",
    "goodText": "Răspunsurile tale nu indică riscuri semnificative acum. Nu eviți situații, nu te preocupă între episoade și nu depinzi de gesturi de siguranță — exact cele trei elemente care se schimbă primele când panica începe să se instaleze.",
    "bands": {
      "good": {
        "label": "Fără tipar de panică",
        "interp": "{name}, răspunsurile tale nu indică un tipar de atacuri de panică instalat."
      },
      "mid": {
        "label": "Tipar în formare — merită urmărit",
        "interp": "{name}, răspunsurile tale arată episoade care au început să își construiască propriile mecanisme de întreținere."
      },
      "low": {
        "label": "Tipar instalat — merită o evaluare",
        "interp": "{name}, răspunsurile tale indică episoade frecvente care afectează deja mai multe zone ale vieții simultan."
      }
    }
  },
  "cta": {
    "lp": "/lp/panica",
    "eyebrow": "Următorul pas",
    "hot": {
      "title": "Ai spus că vrei să rezolvi asta acum",
      "text": "Primul pas e o discuție de 15 minute, în care îți spunem ce se poate măsura în cazul tău și ce se poate corecta concret.",
      "button": "Vreau să rezolv problema"
    },
    "warm": {
      "title": "Care e următorul pas?",
      "text": "La Emmanuel Clinix măsurăm obiectiv nivelul de activare al sistemului nervos și îți arătăm ce se poate corecta. Primul pas e o discuție, nu o programare.",
      "button": "Vreau să văd ce se poate face"
    },
    "nurture": {
      "title": "Când vrei să înțelegi mai bine",
      "text": "Îți explicăm ce se poate măsura obiectiv în cazul atacurilor de panică și ce arată rezultatele unei evaluări. Fără programare, fără obligații.",
      "button": "Află mai multe"
    }
  },
  "note": "Este un instrument de auto-evaluare online, cu rol informativ. Nu este un test medical și nu oferă un diagnostic.",
  "legal": "Acest chestionar este un instrument de auto-evaluare online, cu caracter exclusiv informativ și educațional. Nu este un test medical, nu reprezintă un diagnostic și nu înlocuiește consultul unui medic sau al unui psiholog. Nota și riscurile afișate sunt orientative, generate automat pe baza răspunsurilor pe care le-ați dat, și pot varia în funcție de mulți factori individuali. Riscurile descrise sunt tendințe generale întâlnite în literatura de specialitate, nu predicții despre situația dumneavoastră. Pentru orice problemă de sănătate, adresați-vă unui specialist. Emmanuel Clinix nu garantează rezultate specifice în urma completării acestui test. Simptomele unui atac de panică se pot suprapune cu cele ale unor afecțiuni medicale. Dacă aveți durere în piept apărută pentru prima dată, dificultăți severe de respirație, pierderea cunoștinței sau simptome neobișnuite pentru dumneavoastră, sunați la 112: un atac de panică se poate confirma doar după ce un medic a exclus cauzele fizice."
};
