/**
 * Calitatea somnului — 10 scored questions + the urgency question.
 *
 * GENERATED by `scripts/import-quizzes.mjs` from the client's
 * `Chestionare_Emmanuel_CliniX/chestionar_insomnie.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift.
 */
import type { ScoredQuiz } from "@/content/scored-quizzes";

export const SOMN: ScoredQuiz = {
  "slug": "somn",
  "route": "somn",
  "seo": {
    "title": "Calitatea somnului — test de auto-evaluare",
    "description": "Test de auto-evaluare a calității somnului: 11 întrebări, o notă de la 1 la 10 și riscurile pe care le indică răspunsurile tale."
  },
  "hero": {
    "eyebrow": "Test de auto-evaluare · 11 întrebări",
    "title": "Calitatea somnului",
    "subtitle": "Cât de bine te reface, de fapt, somnul tău?",
    "lead": "Răspunde sincer la cele 11 întrebări de mai jos, gândindu-te la ultima lună. La final primești o notă de la 1 la 10 și riscurile concrete pe care le indică răspunsurile tale.",
    "startButton": "Începe testul →"
  },
  "scoreLabel": "Nota ta",
  "questions": [
    {
      "text": "Cât durează, în mod obișnuit, până adormi seara?",
      "options": [
        {
          "label": "Sub 15 minute",
          "score": 10
        },
        {
          "label": "15–30 de minute",
          "score": 7
        },
        {
          "label": "30–60 de minute",
          "score": 4
        },
        {
          "label": "Peste o oră, aproape în fiecare seară",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 72,
      "risk": {
        "title": "Adormire care devine o luptă zilnică",
        "text": "Când adormirea durează constant peste o oră, creierul începe să asocieze patul cu starea de veghe și efort. Asociația se consolidează în câteva săptămâni și menține insomnia chiar după ce cauza inițială dispare."
      }
    },
    {
      "text": "Cât de des te trezești în timpul nopții?",
      "options": [
        {
          "label": "Rar sau deloc",
          "score": 10
        },
        {
          "label": "O dată, adorm repede la loc",
          "score": 7
        },
        {
          "label": "De 2–3 ori pe noapte",
          "score": 4
        },
        {
          "label": "De mai multe ori — noaptea e fragmentată",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 75,
      "risk": {
        "title": "Somn fragmentat, fără faze profunde",
        "text": "Trezirile repetate întrerup fazele profunde, în care creierul își face curățenia metabolică și consolidează memoria. Poți petrece opt ore în pat și să nu obții niciun beneficiu real."
      }
    },
    {
      "text": "Te trezești dimineața mai devreme decât ai vrea și nu mai poți readormi?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Aproape în fiecare dimineață",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 68,
      "risk": {
        "title": "Trezire matinală precoce",
        "text": "Trezirea constantă cu una–două ore mai devreme, fără posibilitatea de a readormi, e unul dintre semnele cel mai des asociate cu dereglarea ritmului circadian și cu tulburările de dispoziție. Rareori se corectează de la sine."
      }
    },
    {
      "text": "Cât de odihnit te simți la trezire?",
      "options": [
        {
          "label": "Complet odihnit",
          "score": 10
        },
        {
          "label": "Destul de odihnit",
          "score": 7
        },
        {
          "label": "Puțin odihnit — pornesc greu",
          "score": 4
        },
        {
          "label": "Deloc — mă trezesc mai obosit decât m-am culcat",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 70,
      "risk": {
        "title": "Somn care nu mai repară",
        "text": "Când orele dormite nu produc odihnă, problema nu e durata, ci calitatea arhitecturii somnului. E stadiul în care oamenii încep să compenseze cu cafeină, ceea ce deteriorează somnul următor."
      }
    },
    {
      "text": "Câte ore dormi, în medie, pe noapte?",
      "options": [
        {
          "label": "7–8 ore",
          "score": 10
        },
        {
          "label": "6–7 ore",
          "score": 7
        },
        {
          "label": "5–6 ore",
          "score": 4
        },
        {
          "label": "Sub 5 ore",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 85,
      "risk": {
        "title": "Deficit de somn care se acumulează",
        "text": "Sub șase ore constant, deficitul nu se resetează în weekend — se adună. Efectele documentate includ scăderea imunității, creșterea tensiunii arteriale și declin măsurabil al memoriei de lucru."
      }
    },
    {
      "text": "Cât de des folosești telefonul, laptopul sau televizorul în pat, înainte să adormi?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "În fiecare seară, până adorm",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 45,
      "risk": {
        "title": "Semnal de adormire blocat chimic",
        "text": "Lumina ecranelor seara întârzie eliberarea de melatonină cu una–două ore, iar conținutul ține creierul activ exact când ar trebui să încetinească. Efectul se acumulează și mută treptat ora de adormire tot mai târziu."
      }
    },
    {
      "text": "Cât de constant e programul tău de somn (ora de culcare și de trezire)?",
      "options": [
        {
          "label": "Foarte constant, inclusiv în weekend",
          "score": 10
        },
        {
          "label": "Destul de constant, cu mici variații",
          "score": 7
        },
        {
          "label": "Variabil — diferențe de 2–3 ore de la o zi la alta",
          "score": 4
        },
        {
          "label": "Haotic — nu există niciun tipar",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 58,
      "risk": {
        "title": "Ceas biologic dereglat",
        "text": "Ritmul circadian se reglează după consecvență, nu după numărul de ore. Variațiile mari produc un efect asemănător decalajului de fus orar, trăit în fiecare săptămână, fără să pleci nicăieri."
      }
    },
    {
      "text": "Cât de des consumi cafea, energizante sau alcool după ora 16:00?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Aproape zilnic",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 52,
      "risk": {
        "title": "Somn sabotat chimic seara",
        "text": "Cofeina are un timp de înjumătățire de aproximativ șase ore, deci o cafea la ora 16:00 e încă activă la miezul nopții. Alcoolul ajută la adormire, dar suprimă fazele profunde și produce treziri în a doua parte a nopții."
      }
    },
    {
      "text": "Cât de des rămâi în pat cu mintea activă, gândindu-te la ce ai de făcut sau la ce te apasă?",
      "options": [
        {
          "label": "Rar sau deloc",
          "score": 10
        },
        {
          "label": "Ocazional",
          "score": 7
        },
        {
          "label": "Deseori — majoritatea serilor",
          "score": 4
        },
        {
          "label": "În fiecare seară — nu se oprește",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 78,
      "risk": {
        "title": "Pat asociat cu starea de veghe",
        "text": "Timpul petrecut treaz în pat învață creierul că locul acela e pentru gândit, nu pentru dormit. E mecanismul central prin care insomnia ocazională se transformă în insomnie cronică."
      }
    },
    {
      "text": "Cât de des îți afectează lipsa somnului dispoziția, concentrarea sau relațiile?",
      "options": [
        {
          "label": "Deloc",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Deseori",
          "score": 4
        },
        {
          "label": "Zilnic — se vede în tot ce fac",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 88,
      "risk": {
        "title": "Efecte care ies din dormitor",
        "text": "Privarea cronică de somn scade controlul emoțional și capacitatea de decizie mai mult decât realizează majoritatea oamenilor. Costul apare în relații și în muncă, iar cauza rămâne rareori identificată corect."
      }
    }
  ],
  "urgency": {
    "text": "Cât de repede vrei să rezolvi asta?",
    "options": [
      {
        "label": "Acum, urgent",
        "urgency": "hot"
      },
      {
        "label": "În următoarele luni",
        "urgency": "warm"
      },
      {
        "label": "Doar mă documentez deocamdată",
        "urgency": "nurture"
      }
    ]
  },
  "combos": [
    {
      "q": [
        4,
        9
      ],
      "max": 4,
      "weight": 100,
      "risk": {
        "title": "Deficit cronic cu efecte deja vizibile",
        "text": "Dormi constant prea puțin, iar efectele se văd deja în dispoziție și în concentrare. Din acest punct, recuperarea nu se mai face prin câteva nopți bune — deficitul acumulat necesită corecție structurată."
      }
    },
    {
      "q": [
        0,
        8
      ],
      "max": 4,
      "weight": 96,
      "risk": {
        "title": "Insomnie care s-a autonomizat",
        "text": "Adormirea grea, combinată cu mintea activă în pat, este mecanismul exact prin care insomnia devine cronică. Creierul a învățat deja asocierea, iar ea persistă independent de cauza care a pornit-o."
      }
    },
    {
      "q": [
        1,
        3
      ],
      "max": 4,
      "weight": 90,
      "risk": {
        "title": "Somn prezent, dar fără efect reparator",
        "text": "Trezirile repetate și lipsa senzației de odihnă arată o arhitectură a somnului deteriorată, nu o problemă de durată. Fazele profunde sunt cele care lipsesc, iar ele nu se recuperează prin ore în plus."
      }
    },
    {
      "q": [
        5,
        7
      ],
      "max": 4,
      "weight": 74,
      "risk": {
        "title": "Somn sabotat înainte de culcare",
        "text": "Ecranele seara și stimulentele după-amiaza acționează pe aceleași mecanisme: întârzie adormirea și reduc profunzimea somnului. Sunt și cei doi factori care se corectează cel mai repede."
      }
    },
    {
      "q": [
        2,
        6
      ],
      "max": 4,
      "weight": 70,
      "risk": {
        "title": "Ritm circadian ieșit din sincron",
        "text": "Trezirea precoce, combinată cu un program neregulat, arată un ceas biologic care nu mai are repere stabile. Fără resincronizare, tiparul se adâncește lună de lună."
      }
    }
  ],
  "lead": {
    "title": "Aproape gata!",
    "text": "Completează datele de mai jos pentru a-ți vedea nota finală și analiza de risc.",
    "submit": "Vezi rezultatele mele →"
  },
  "result": {
    "risksHeading": "Ce riscuri indică răspunsurile tale",
    "risksSub": "Traiectoriile documentate cel mai frecvent la răspunsuri similare, în lipsa unei intervenții.",
    "closing": "<strong>De reținut:</strong> niciunul nu e un traseu obligatoriu. Somnul este una dintre funcțiile care se pot măsura cel mai precis — iar când se vede exact unde se rupe, se poate corecta.",
    "goodHeading": "Analiza răspunsurilor tale",
    "goodText": "Răspunsurile tale nu indică riscuri semnificative acum. Adormi ușor, dormi continuu și te trezești odihnit — cele trei elemente pe care se sprijină tot restul.",
    "bands": {
      "good": {
        "label": "Somn sănătos",
        "interp": "{name}, răspunsurile tale indică un somn care își face treaba: te reface și îți susține ziua."
      },
      "mid": {
        "label": "Somn deteriorat — tipar în formare",
        "interp": "{name}, răspunsurile tale arată un somn care a început să se degradeze și să își construiască propriile mecanisme de întreținere."
      },
      "low": {
        "label": "Somn sever afectat — merită o evaluare",
        "interp": "{name}, răspunsurile tale indică o problemă de somn instalată, cu efecte care se văd deja în timpul zilei."
      }
    }
  },
  "cta": {
    "lp": "/lp/somn",
    "eyebrow": "Următorul pas",
    "hot": {
      "title": "Ai spus că vrei să rezolvi asta acum",
      "text": "Primul pas e o discuție de 15 minute, în care îți spunem ce se poate măsura în cazul tău și unde anume se rupe somnul.",
      "button": "Vreau să rezolv problema"
    },
    "warm": {
      "title": "Care e următorul pas?",
      "text": "La Emmanuel Clinix măsurăm obiectiv ce se întâmplă în creier în timpul somnului și îți arătăm ce se poate corecta. Primul pas e o discuție, nu o programare.",
      "button": "Vreau să văd ce se poate face"
    },
    "nurture": {
      "title": "Când vrei să înțelegi mai bine",
      "text": "Îți explicăm cum se măsoară obiectiv calitatea somnului și ce arată o evaluare. Fără programare, fără obligații.",
      "button": "Află mai multe"
    }
  },
  "note": "Este un instrument de auto-evaluare online, cu rol informativ. Nu este un test medical și nu oferă un diagnostic.",
  "legal": "Acest chestionar este un instrument de auto-evaluare online, cu caracter exclusiv informativ și educațional. Nu este un test medical, nu reprezintă un diagnostic și nu înlocuiește consultul unui medic sau al unui psiholog. Nota și riscurile afișate sunt orientative, generate automat pe baza răspunsurilor pe care le-ați dat, și pot varia în funcție de mulți factori individuali. Riscurile descrise sunt tendințe generale întâlnite în literatura de specialitate, nu predicții despre situația dumneavoastră. Pentru orice problemă de sănătate, adresați-vă unui specialist. Emmanuel Clinix nu garantează rezultate specifice în urma completării acestui test."
};
