/**
 * Nivelul de stres — 11 scored questions + the urgency question.
 *
 * GENERATED by `scripts/import-quizzes.mjs` from the client's
 * `Chestionare_Emmanuel_CliniX/chestionar_stres.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift.
 */
import type { ScoredQuiz } from "@/content/scored-quizzes";

export const STRES: ScoredQuiz = {
  "slug": "stres",
  "route": "stres",
  "seo": {
    "title": "Nivelul de stres — test de auto-evaluare",
    "description": "Test de auto-evaluare a nivelului de stres: 12 întrebări, o notă de la 1 la 10 și riscurile pe care le indică răspunsurile tale."
  },
  "hero": {
    "eyebrow": "Test de auto-evaluare · 12 întrebări",
    "title": "Nivelul de stres",
    "subtitle": "Cât de mult stres acumulezi, de fapt?",
    "lead": "Răspunde sincer la cele 12 întrebări de mai jos. La final primești o notă de la 1 la 10 și riscurile concrete pe care le indică răspunsurile tale, dacă situația rămâne așa cum e acum.",
    "startButton": "Începe testul →"
  },
  "scoreLabel": "Nota ta",
  "questions": [
    {
      "text": "Cât de des te simți copleșit de responsabilitățile zilnice?",
      "options": [
        {
          "label": "Niciodată — le gestionez fără să mă apese",
          "score": 10
        },
        {
          "label": "Rar — doar în perioadele aglomerate",
          "score": 7
        },
        {
          "label": "Deseori — în majoritatea săptămânilor",
          "score": 4
        },
        {
          "label": "Aproape zilnic — nu mai văd capătul",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 55,
      "risk": {
        "title": "Sistem nervos blocat în alertă",
        "text": "Corpul rămâne în alarmă permanentă și produce cortizol continuu. Scad concentrarea și calitatea deciziilor — iar greșelile adaugă presiune peste presiunea existentă."
      }
    },
    {
      "text": "De cât timp durează starea asta de tensiune?",
      "options": [
        {
          "label": "Nu e cazul — nu mă simt tensionat",
          "score": 10
        },
        {
          "label": "De câteva săptămâni, legat de o situație punctuală",
          "score": 7
        },
        {
          "label": "De câteva luni",
          "score": 4
        },
        {
          "label": "De peste un an — nu mai știu cum e altfel",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 90,
      "risk": {
        "title": "Stres trecut în stadiul cronic",
        "text": "După aproximativ șase luni de tensiune continuă, organismul nu mai revine singur la linia de bază. Din acest punct, odihna și concediul nu mai produc refacere reală."
      }
    },
    {
      "text": "Cât de des ai dureri fizice fără cauză medicală clară (cap, umeri, gât, spate, stomac)?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "Rar",
          "score": 7
        },
        {
          "label": "Săptămânal",
          "score": 4
        },
        {
          "label": "Aproape zilnic",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 62,
      "risk": {
        "title": "Tensiune somatizată în corp",
        "text": "Durerile fără cauză medicală sunt tensiune musculară menținută non-stop, inclusiv în somn. Netratate, evoluează spre contracturi cervicale cronice, migrene tensionale și probleme digestive."
      }
    },
    {
      "text": "Cât de greu îți este să te oprești din a te gândi la muncă sau la probleme când ești acasă?",
      "options": [
        {
          "label": "Deloc greu — închid subiectul ușor",
          "score": 10
        },
        {
          "label": "Rar mi se întâmplă să rămân blocat pe ele",
          "score": 7
        },
        {
          "label": "Deseori — gândurile revin toată seara",
          "score": 4
        },
        {
          "label": "Aproape mereu — mintea nu se oprește niciodată",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 50,
      "risk": {
        "title": "Fără perioade reale de refacere",
        "text": "Creierul consumă resurse și seara, iar somnul rămâne superficial chiar dacă orele par suficiente. E tiparul care precede epuizarea cu șase până la douăsprezece luni."
      }
    },
    {
      "text": "Cât de des îți pierzi răbdarea cu cei apropiați din lucruri mărunte?",
      "options": [
        {
          "label": "Niciodată — am răbdarea obișnuită",
          "score": 10
        },
        {
          "label": "Rar, în zilele grele",
          "score": 7
        },
        {
          "label": "Deseori — cei din jur au început să observe",
          "score": 4
        },
        {
          "label": "Aproape zilnic — explodez din nimicuri și apoi regret",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 65,
      "risk": {
        "title": "Eroziune în relațiile apropiate",
        "text": "Rezerva de autocontrol se consumă la muncă și nu mai rămâne nimic pentru acasă. Cei din jur se retrag treptat — o pierdere care se recuperează greu, chiar și după ce stresul dispare."
      }
    },
    {
      "text": "Cât de des ai senzația că nu ai control asupra propriei vieți?",
      "options": [
        {
          "label": "Niciodată — eu decid cum arată zilele mele",
          "score": 10
        },
        {
          "label": "Rar, în perioade dificile",
          "score": 7
        },
        {
          "label": "Deseori — reacționez la ce apare, nu conduc eu",
          "score": 4
        },
        {
          "label": "Aproape mereu — sunt dus de val",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 75,
      "risk": {
        "title": "Pierderea sentimentului de control",
        "text": "Când efortul nu mai pare să schimbe rezultatul, creierul taie motivația ca să economisească resurse. E cel mai puternic predictor documentat al trecerii de la stres la depresie."
      }
    },
    {
      "text": "Cât de des recurgi la mâncare, dulciuri, alcool, țigări sau scroll pe telefon ca să te calmezi?",
      "options": [
        {
          "label": "Rar sau deloc",
          "score": 10
        },
        {
          "label": "Ocazional, după zile grele",
          "score": 7
        },
        {
          "label": "Deseori — e reflexul meu principal de calmare",
          "score": 4
        },
        {
          "label": "Zilnic — nu mai reușesc să mă relaxez altfel",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 70,
      "risk": {
        "title": "Reglare prin obiceiuri care se întorc împotrivă",
        "text": "Scad tensiunea în câteva minute și o cresc pe termen lung. Pragul urcă constant — mai mult, mai des — și așa se formează dependențele funcționale."
      }
    },
    {
      "text": "Cum dormi în perioadele stresante?",
      "options": [
        {
          "label": "La fel de bine ca de obicei",
          "score": 10
        },
        {
          "label": "Adorm ceva mai greu, dar dorm bine",
          "score": 7
        },
        {
          "label": "Prost — adorm greu sau mă trezesc noaptea",
          "score": 4
        },
        {
          "label": "Foarte prost — am nopți în care aproape nu dorm",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 80,
      "risk": {
        "title": "Somnul, primul mecanism care cedează",
        "text": "Dormi prost fiindcă ești stresat și devii mai stresat fiindcă dormi prost. După câteva luni, insomnia devine independentă de cauza care a pornit-o."
      }
    },
    {
      "text": "Cât de des reușești să te deconectezi complet — o zi fără muncă, fără telefon, fără să te gândești la ce ai de rezolvat?",
      "options": [
        {
          "label": "Regulat — cel puțin o dată pe săptămână",
          "score": 10
        },
        {
          "label": "Câteva zile pe lună",
          "score": 7
        },
        {
          "label": "Rar — poate o dată la câteva luni",
          "score": 4
        },
        {
          "label": "Practic niciodată",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 45,
      "risk": {
        "title": "Sistem care nu mai trece în modul de refacere",
        "text": "Sistemul nervos rămâne fixat în alertă și pierde capacitatea de a comuta pe refacere. Se vede în energia de dimineață, în răcelile dese și în odihna care nu mai odihnește."
      }
    },
    {
      "text": "Ai pe cineva apropiat cu care discuți deschis despre ce te apasă?",
      "options": [
        {
          "label": "Da, mai multe persoane",
          "score": 10
        },
        {
          "label": "Da, cel puțin o persoană",
          "score": 7
        },
        {
          "label": "Rar — păstrez aproape tot pentru mine",
          "score": 4
        },
        {
          "label": "Nu — nu discut asta cu nimeni",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 55,
      "risk": {
        "title": "Izolare emoțională",
        "text": "Același nivel de stres are impact aproape dublu fără cineva cu care să vorbești deschis. Iar cu cât starea durează, cu atât scade disponibilitatea de a mai cere ajutor."
      }
    },
    {
      "text": "Cât de des ai avut, în ultimele luni, momente în care ai simțit că nu mai poți continua în ritmul ăsta?",
      "options": [
        {
          "label": "Niciodată",
          "score": 10
        },
        {
          "label": "O dată sau de două ori",
          "score": 7
        },
        {
          "label": "De mai multe ori",
          "score": 4
        },
        {
          "label": "Constant — e gândul de fundal al zilelor mele",
          "score": 1
        }
      ],
      "triggers": [
        4,
        1
      ],
      "weight": 95,
      "risk": {
        "title": "Rezerve aproape consumate",
        "text": "Nu e slăbiciune, e semnalul obiectiv că rezervele s-au epuizat. De obicei se termină în epuizare completă sau într-o decizie luată sub presiune, care se regretă."
      }
    }
  ],
  "urgency": {
    "text": "Cât de repede vrei să rezolvi asta?",
    "options": [
      {
        "label": "Acum, urgent",
        "urgency": "hot"
      },
      {
        "label": "În următoarele luni",
        "urgency": "warm"
      },
      {
        "label": "Doar mă documentez deocamdată",
        "urgency": "nurture"
      }
    ]
  },
  "combos": [
    {
      "q": [
        1,
        7
      ],
      "max": 4,
      "weight": 100,
      "risk": {
        "title": "Stres cronic peste un somn deteriorat",
        "text": "Fără somn profund, cortizolul rămâne ridicat și dimineața — corpul nu mai are nicio fereastră de revenire în 24 de ore. De aici, odihna singură nu mai corectează nimic."
      }
    },
    {
      "q": [
        5,
        10
      ],
      "max": 4,
      "weight": 98,
      "risk": {
        "title": "Faza dinaintea prăbușirii",
        "text": "Funcționezi impecabil la exterior, dar fără rezerve la interior — motiv pentru care nimeni din jur nu intervine la timp. Evoluează frecvent spre burnout complet sau episod depresiv în șase până la douăsprezece luni."
      }
    },
    {
      "q": [
        2,
        8
      ],
      "max": 4,
      "weight": 92,
      "risk": {
        "title": "Corpul semnalează, dar nu primește refacere",
        "text": "Dureri fizice recurente fără nicio pauză reală înseamnă un sistem care nu iese niciodată din alertă. Stadiul următor nu e o durere mai mare, ci o cădere bruscă."
      }
    },
    {
      "q": [
        6,
        7
      ],
      "max": 4,
      "weight": 88,
      "risk": {
        "title": "Cerc de reglare care se închide",
        "text": "Substanțele și scrollul de seară fragmentează somnul, iar somnul prost crește a doua zi nevoia de calmare rapidă. Așa devin obiceiurile banale dependențe reale, în câteva luni."
      }
    },
    {
      "q": [
        4,
        9
      ],
      "max": 4,
      "weight": 85,
      "risk": {
        "title": "Izolare care se adâncește singură",
        "text": "Iritabilitatea îi îndepărtează pe cei din jur, iar tu rămâi cu și mai puțin sprijin decât la început. E exact ce transformă un stres temporar într-unul de lungă durată."
      }
    },
    {
      "q": [
        0,
        3
      ],
      "max": 4,
      "weight": 82,
      "risk": {
        "title": "Minte în activitate continuă",
        "text": "Practic nicio oră de repaus mental real în 24. Efectul e măsurabil: memorie de lucru redusă, decizii mai slabe, greșeli la lucruri simple."
      }
    }
  ],
  "lead": {
    "title": "Aproape gata!",
    "text": "Completează datele de mai jos pentru a-ți vedea nota finală și analiza de risc.",
    "submit": "Vezi rezultatele mele →"
  },
  "result": {
    "risksHeading": "Ce riscuri indică răspunsurile tale",
    "risksSub": "Traiectoriile documentate cel mai frecvent la răspunsuri similare, în lipsa unei intervenții.",
    "closing": "<strong>De reținut:</strong> niciunul nu e un traseu obligatoriu. Stresul cronic se poate măsura obiectiv, iar când mecanismul e vizibil, devine corectabil.",
    "goodHeading": "Analiza răspunsurilor tale",
    "goodText": "Răspunsurile tale nu indică riscuri semnificative acum. Somnul, deconectarea și rețeaua de sprijin funcționează — exact cele trei elemente care cedează primele într-o perioadă aglomerată.",
    "bands": {
      "good": {
        "label": "Nivel de stres gestionabil",
        "interp": "{name}, răspunsurile tale indică un nivel de stres pe care îl gestionezi în prezent fără consecințe majore."
      },
      "mid": {
        "label": "Nivel moderat — acumulare în curs",
        "interp": "{name}, răspunsurile tale arată un stres care nu s-a stabilizat, ci se acumulează."
      },
      "low": {
        "label": "Nivel ridicat — merită o evaluare",
        "interp": "{name}, răspunsurile tale indică un stres care afectează deja mai multe zone simultan."
      }
    }
  },
  "cta": {
    "lp": "/lp/stres",
    "eyebrow": "Următorul pas",
    "hot": {
      "title": "Ai spus că vrei să rezolvi asta acum",
      "text": "Primul pas e o discuție de 15 minute, în care îți spunem exact ce se poate măsura și ce se poate corecta în situația ta.",
      "button": "Vreau să rezolv problema"
    },
    "warm": {
      "title": "Care e următorul pas?",
      "text": "La Emmanuel Clinix măsurăm obiectiv ce se întâmplă în sistemul tău nervos și îți arătăm ce se poate corecta. Primul pas e o discuție, nu o programare.",
      "button": "Vreau să văd ce se poate face"
    },
    "nurture": {
      "title": "Când vrei să înțelegi mai bine",
      "text": "Îți explicăm cum se măsoară obiectiv stresul cronic și ce arată rezultatele. Fără programare, fără obligații.",
      "button": "Află mai multe"
    }
  },
  "note": "Este un instrument de auto-evaluare online, cu rol informativ. Nu este un test medical și nu oferă un diagnostic.",
  "legal": "Acest chestionar este un instrument de auto-evaluare online, cu caracter exclusiv informativ și educațional. Nu este un test medical, nu reprezintă un diagnostic și nu înlocuiește consultul unui medic sau al unui psiholog. Nota și riscurile afișate sunt orientative, generate automat pe baza răspunsurilor pe care le-ați dat, și pot varia în funcție de mulți factori individuali. Riscurile descrise sunt tendințe generale întâlnite în literatura de specialitate, nu predicții despre situația dumneavoastră. Pentru orice problemă de sănătate, adresați-vă unui specialist. Emmanuel Clinix nu garantează rezultate specifice în urma completării acestui test."
};
