import Link from "next/link";
import type { BrainmapLp } from "@/content/campaign-lps";
import { LpBrainmapForm } from "@/components/lp/LpBrainmapForm";
import { LpBrainmapScripts } from "@/components/lp/LpBrainmapScripts";
import { LpBrainmapProof } from "@/components/lp/LpBrainmapProof";
import "./lp-brainmap.css";

/**
 * The client's BrainMap campaign LP, as one shared template.
 *
 * Their source HTML marks every block `[FIX]` (identical on all eight pages) or
 * `[NIȘAT]` (rewritten per condition). This component is the FIX half, ported
 * verbatim — same markup, same classes, same section order, driven by
 * `components/lp/lp-brainmap.css` (their stylesheet, scoped). The NIȘAT half
 * arrives as `lp` (`content/campaign-lps/<slug>.ts`, generated by
 * `scripts/import-brainmap-lps.mjs`).
 *
 * Section order is load-bearing and deliberate — the VSL sits AFTER the visitor
 * has recognized themselves and accepted that what's missing is a measurement,
 * so it answers "fine, and what is this?" rather than opening with it. Don't
 * reorder without the client.
 *
 * Two things are still placeholders, waiting on the client's assets: the VSL
 * player and the three testimonial videos are inert frames, exactly as they
 * ship in the source.
 */
export function LpBrainmapTemplate({ lp }: { lp: BrainmapLp }) {
  const rootId = `lp-brainmap-${lp.slug}`;

  return (
    <div
      className="lp-brainmap"
      id={rootId}
      // The stylesheet's `--f` is the client's font stack; bind it to the
      // self-hosted next/font face instead of their external Google Fonts link.
      style={{ ["--f" as string]: "var(--font-jakarta), system-ui, -apple-system, sans-serif" }}
    >
      <LpBrainmapScripts rootId={rootId} />

      <header>
        <div className="hd">
          <div className="brand">
            <BrandMark stroke="#0B2A33" />
            <span>Emmanuel CliniX</span>
          </div>
          <div className="hd-r">
            <a className="tel" href="tel:+40790099070">
              <svg width="15" height="15" viewBox="0 0 16 16" aria-hidden="true">
                <path
                  d="M2 3.5C2 2.7 2.7 2 3.5 2h1.2c.6 0 1.1.4 1.2 1l.4 2c.1.5-.1 1-.5 1.2l-.9.5c.7 1.5 1.9 2.7 3.4 3.4l.5-.9c.3-.4.7-.6 1.2-.5l2 .4c.6.1 1 .6 1 1.2v1.2c0 .8-.7 1.5-1.5 1.5C7.6 14 2 8.4 2 3.5Z"
                  fill="currentColor"
                />
              </svg>
              +40 790 099 070
            </a>
            <a className="btn btn-dark btn-sm" href="#aplica">
              Aplică pentru BrainMap
            </a>
          </div>
        </div>
      </header>

      {/* ═══ 1 · HERO ═══ */}
      <section className="hero">
        <div className="wrap">
          {/* The client tints two to four words with an <em>; their copy, not user input. */}
          <h1 dangerouslySetInnerHTML={{ __html: lp.hero.titleHtml }} />
          <p className="lede">{lp.hero.lede}</p>

          <div className="hero-cta">
            <a className="btn btn-lg" href="#aplica">
              Aplică pentru BrainMap →
            </a>
            <p className="micro">Completezi un formular scurt. Te sunăm noi.</p>
          </div>

          {/* The visual signature: an EEG trace. Identical on every page. */}
          <div className="trace" aria-hidden="true">
            <svg viewBox="0 0 960 90" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path
                d="M0 62 L52 62 L64 40 L76 74 L88 30 L100 62 L152 62 L164 50 L176 68 L188 44 L200 62 L268 62 L280 26 L292 78 L304 36 L316 62 L392 62 L404 48 L416 70 L428 42 L440 62 L512 62 L524 34 L536 72 L548 28 L560 62 L636 62 L648 52 L660 66 L672 46 L684 62 L752 62 L764 32 L776 76 L788 38 L800 62 L960 62"
                stroke="#2DCEE6"
                strokeWidth="1.6"
                strokeLinecap="round"
                strokeLinejoin="round"
                opacity=".55"
              />
              <path d="M0 62 L960 62" stroke="#1E4B56" strokeWidth="1" opacity=".5" />
            </svg>
          </div>

          <div className="facts">
            {[
              "30 de minute scanarea",
              "Fără radiații, fără ace",
              "Interpretare în aceeași vizită",
              "Fără trimitere de la medicul de familie",
            ].map((fact) => (
              <span className="fact" key={fact}>
                <i>✓</i>
                {fact}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ═══ 2 · IDENTIFICARE ═══ */}
      <section className="sec">
        <div className="wrap">
          <div className="center head">
            <p className="eyebrow">Situația de acum</p>
            <h2>Recunoști una dintre situațiile astea?</h2>
          </div>
          <div className="g3">
            {lp.identificare.cards.map((card) => (
              <div className="card" key={card.tag}>
                <span className="tag">{card.tag}</span>
                <p>{card.text}</p>
              </div>
            ))}
          </div>
          <p className="pull">{lp.identificare.pull}</p>
        </div>
      </section>

      {/* ═══ 3 · DE CE NU A ȚINUT ═══ */}
      <section className="sec sec-alt why">
        <div className="narrow">
          <p className="eyebrow">De ce nimic nu a ținut</p>
          <h2>Ai încercat. Și tot acolo ești.</h2>

          <p className="first" style={{ marginTop: "26px" }}>
            {lp.why.tried}
          </p>
          <p>{lp.why.assumption}</p>
          <p>{lp.why.cost}</p>

          <p className="kicker">Nimeni nu ți-a arătat, concret, ce se întâmplă.</p>

          <p>{lp.why.analogy}</p>
          <p style={{ marginBottom: 0 }}>E greu să repari ceva ce n-ai văzut niciodată cum arată.</p>
        </div>
      </section>

      {/* ═══ 4 · VSL GENERAL ═══ — the same video on every page. */}
      <section className="sec sec-dark" id="video">
        <div className="wrap">
          <div className="center head vsl-head">
            <p className="eyebrow">Ce urmează</p>
            <h2>Uite ce măsurăm, înainte să spunem ceva</h2>
            <p className="lede" style={{ marginTop: "18px" }}>
              Patru minute și jumătate. Cristi îți arată ce este BrainMap, cum arată o hartă reală și de
              ce pornim de la măsurătoare, nu de la simptom.
            </p>
          </div>

          {/* [PLACEHOLDER] Swap for the real embed once the video lands. */}
          <div className="player">
            <div className="play" role="button" tabIndex={0} aria-label="Pornește video">
              <svg width="22" height="26" viewBox="0 0 22 26" aria-hidden="true">
                <path d="M0 0 L22 13 L0 26 Z" fill="#fff" />
              </svg>
            </div>
            <div className="p-meta">
              <b>Emmanuel CliniX</b>
              <span>4:30 min</span>
            </div>
          </div>

          <div className="vpoints">
            <div className="vpt">
              <b>Ce citesc senzorii</b>
              <span>Activitatea electrică pe care creierul o produce oricum, în fiecare secundă.</span>
            </div>
            <div className="vpt">
              <b>Cum arată o hartă</b>
              <span>Zone prea active, zone prea lente. Vezi una reală, explicată pe loc.</span>
            </div>
            <div className="vpt">
              <b>Ce faci cu ea</b>
              <span>De ce o măsurătoare schimbă discuția despre ce urmează.</span>
            </div>
          </div>

          <div className="cta-blk">
            <a className="btn btn-lg" href="#aplica">
              Aplică pentru BrainMap →
            </a>
          </div>
        </div>
      </section>

      {/* ═══ 5 · MECANISMUL ═══ — repeats the video in text, because most
          visitors never open it and the page has to stand on its own. */}
      <section className="sec">
        <div className="wrap">
          <div className="center head">
            <p className="eyebrow">Mecanismul</p>
            <h2>
              Nu pornim de la simptom.
              <br />
              Pornim de la măsurătoare.
            </h2>
          </div>
          <div className="steps">
            <div className="step">
              <div className="n">30 min</div>
              <div>
                <h3>Scanarea</h3>
                <p>
                  Îți punem o cască cu senzori. Stai pe scaun, cu hainele pe tine, cu ochii închiși și
                  apoi deschiși. Senzorii citesc activitatea electrică pe care creierul tău o produce
                  oricum, în fiecare secundă. Ca un microfon care ascultă creierul vorbind.
                </p>
              </div>
            </div>
            <div className="step">
              <div className="n">Pe ecran</div>
              <div>
                <h3>Harta activității creierului tău</h3>
                <p>{lp.mapSentence}</p>
              </div>
            </div>
            <div className="step">
              <div className="n">Aceeași zi</div>
              <div>
                <h3>Interpretarea, pe loc</h3>
                <p>
                  Îți explicăm harta pe înțelesul tău, în aceeași vizită. Pleci știind care e situația și
                  ce urmează.
                </p>
              </div>
            </div>
          </div>
          <div className="note-box">
            <p>
              Nu îți intră nimic în corp. Nu ți se administrează nimic. Fără radiații, fără ace, fără
              durere. Te ridici de pe scaun și îți continui ziua exact cum ai plănuit-o.
            </p>
          </div>
        </div>
      </section>

      {/* ═══ 6 · CE INCLUDE VIZITA ═══ */}
      <section className="sec sec-alt">
        <div className="narrow">
          <div className="center head">
            <p className="eyebrow">Ce include vizita</p>
            <h2>O oră în total. Atât.</h2>
          </div>
          <div className="stack">
            <div className="srow">
              <div className="ico">✓</div>
              <div>
                <h4>Scanarea BrainMap</h4>
                <p>30 de minute, cu hainele pe tine.</p>
              </div>
            </div>
            <div className="srow">
              <div className="ico">✓</div>
              <div>
                <h4>Interpretarea hărții, pe loc</h4>
                <p>În cuvinte pe care le înțelegi, nu în termeni medicali.</p>
              </div>
            </div>
            <div className="srow">
              <div className="ico">✓</div>
              <div>
                <h4>Consult psihologic, în aceeași vizită</h4>
                <p>Fără o a doua programare.</p>
              </div>
            </div>
            <div className="srow">
              <div className="ico">✓</div>
              <div>
                <h4>PDF pe mail sau pe WhatsApp</h4>
                <p>
                  Interpretarea completă și recomandări personalizate pe care le poți aplica acasă, pe
                  cont propriu, fără costuri în plus.
                </p>
              </div>
            </div>
            <div className="sfoot">
              <div className="lbl">Tot ce e mai sus, într-o singură vizită</div>
              <div className="num">1.200 lei</div>
            </div>
          </div>
          <p className="keep">Harta și PDF-ul rămân ale tale, indiferent ce alegi să faci mai departe.</p>
          <div className="cta-blk">
            <a className="btn btn-lg" href="#aplica">
              Aplică pentru BrainMap →
            </a>
          </div>
        </div>
      </section>

      {/* ═══ 7 · DOVEZI ═══ — the same three testimonials on every page. */}
      <section className="sec" id="rezultate">
        <div className="wrap">
          <div className="center head">
            <p className="eyebrow">Dovezi</p>
            <h2>Nu trebuie să ne crezi pe cuvânt</h2>
            <p className="lede" style={{ maxWidth: "600px", marginTop: "18px" }}>
              Ernesto, Gabriela și Paulina au început exact de unde ești tu acum: de la harta creierului
              lor.
            </p>
          </div>
          <LpBrainmapProof />
        </div>
      </section>

      {/* ═══ 8 · CALIFICARE ═══ — the right column is the filter that keeps the
          positioning premium; only the left one is per-condition. */}
      <section className="sec sec-alt">
        <div className="wrap">
          <div className="center head">
            <p className="eyebrow">Ca să fim onești</p>
            <h2>Pentru cine e și pentru cine nu e</h2>
          </div>
          <div className="qual">
            <div className="ql">
              <h3>E pentru tine dacă</h3>
              <ul>
                {[
                  ...lp.qualify.fits,
                  "Ai încercat deja mai multe lucruri și niciunul nu a ținut",
                  "Vrei să vezi date despre tine, nu sfaturi generale",
                ].map((row) => (
                  <li key={row}>
                    <span className="ico">✓</span>
                    <span>{row}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="ql">
              <h3>Nu aplica dacă</h3>
              <ul>
                {[
                  "Cauți o rețetă rapidă și atât",
                  "Vrei garanția că totul se rezolvă după o singură vizită",
                  "Nu poți veni la o evaluare de o oră, în clinică, în București",
                  "Bugetul pentru evaluare e o problemă chiar acum",
                  ...(lp.qualify.extraExclusion ? [lp.qualify.extraExclusion] : []),
                ].map((row) => (
                  <li key={row}>
                    <span className="ico x">✕</span>
                    <span>{row}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* ═══ 9 · CE PROMITEM ȘI CE NU ═══ */}
      <section className="sec sec-dark">
        <div className="wrap">
          <div className="center head" style={{ marginBottom: "44px" }}>
            <p className="eyebrow">Înainte să aplici</p>
            <h2>Ce îți promitem și ce nu</h2>
          </div>
          <div className="band">
            <div className="sh">◈</div>
            <p>
              <b>Nu îți promitem că se rezolvă totul după o vizită.</b> Îți promitem că pleci de la noi
              știind clar care e problema și ce urmează.
            </p>
          </div>
          <div className="band">
            <div className="sh">◈</div>
            <p>
              <b>Dacă vedem că nu te putem ajuta, îți spunem la telefon.</b> Înainte să plătești ceva și
              înainte să vii la clinică. Nu programăm pe cineva doar ca să programăm.
            </p>
          </div>
          <div className="cta-blk">
            <a className="btn btn-lg" href="#aplica">
              Aplică pentru BrainMap →
            </a>
          </div>
        </div>
      </section>

      {/* ═══ 10 · FAQ ═══ — the first two carry the segment's real objection. */}
      <section className="sec sec-alt" id="faq">
        <div className="narrow">
          <div className="center head">
            <p className="eyebrow">Întrebări</p>
            <h2>FAQ</h2>
          </div>
          <div className="faq">
            {[...lp.faq, ...FIXED_FAQ].map((item) => (
              <details key={item.q}>
                <summary>{item.q}</summary>
                <p>{item.a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* ═══ 11 · FORMULAR ═══ */}
      <section className="sec" id="aplica">
        <div className="narrow">
          <div className="center head">
            <p className="eyebrow">Primul pas</p>
            <h2>{lp.form.title}</h2>
            <p className="lede" style={{ maxWidth: "560px", marginTop: "18px" }}>
              Completează formularul de mai jos. Te sunăm noi în cel mai scurt timp, ca să programăm.
            </p>
          </div>

          {/* What happens after they submit — answers the objection where it appears. */}
          <div className="flow">
            {[
              ["01", "Completezi", "formularul"],
              ["02", "Te sunăm", "și programăm"],
              ["03", "O oră", "în clinică"],
              ["04", "Pleci cu", "harta ta"],
            ].map(([n, a, b]) => (
              <div key={n}>
                <b>{n}</b>
                <span>
                  {a}
                  <br />
                  {b}
                </span>
              </div>
            ))}
          </div>

          <LpBrainmapForm lp={lp} />
        </div>
      </section>

      <footer>
        <div className="wrap">
          <div className="ft">
            <div>
              <div className="brand">
                <BrandMark stroke="#0F323A" />
                <span>Emmanuel CliniX</span>
              </div>
              <div className="ft-tag">Longevity · Wellness · Neuro</div>
            </div>
            <div>
              <h5>Pagină</h5>
              <a href="#video">Video</a>
              <a href="#rezultate">Rezultate</a>
              <a href="#faq">FAQ</a>
              <a href="#aplica">Aplică acum</a>
            </div>
            <div>
              <h5>Contact</h5>
              <a href="mailto:contact@emmanuelclinix.ro">contact@emmanuelclinix.ro</a>
              <a href="tel:+40790099070">+40 790 099 070</a>
            </div>
          </div>
          <div className="legal">
            {lp.legal}
            <br />© 2026 Emmanuel CliniX. Toate drepturile rezervate. ·{" "}
            <Link href="/politica-de-confidentialitate">Politica de confidențialitate</Link> ·{" "}
            <Link href="/termeni-si-conditii">Termeni și condiții</Link>
          </div>
        </div>
      </footer>

      <div className="sticky">
        <span className="s-txt">
          BrainMap · 1.200 lei<i>O oră în clinică, în București</i>
        </span>
        <a className="btn btn-sm" href="#aplica">
          Aplică pentru BrainMap →
        </a>
      </div>
    </div>
  );
}

/** The last five FAQ entries — identical on every page. */
const FIXED_FAQ = [
  { q: "Am nevoie de trimitere de la medicul de familie?", a: "Nu." },
  {
    q: "Iau deja medicamente. Le opresc înainte?",
    a: "Nu opri nimic pe cont propriu. Discuți asta cu medicul care ți le-a prescris. Ne spui la telefon ce iei, ca să ținem cont la interpretare.",
  },
  {
    q: "Ce se întâmplă după scanare?",
    a: "Discutăm ce arată harta și ce opțiuni ai mai departe. Decizi tu. Nu ești obligat la nimic.",
  },
  {
    q: "Cât se așteaptă pentru o programare?",
    a: "Depinde de intervalele libere. Te sunăm în cel mai scurt timp și găsim împreună o oră care ți se potrivește.",
  },
  {
    q: "Ce se întâmplă cu datele mele?",
    a: "Rămân confidențiale. Sunt folosite doar pentru evaluarea ta și nu se transmit mai departe.",
  },
];

function BrandMark({ stroke }: { stroke: string }) {
  return (
    <svg width="26" height="26" viewBox="0 0 26 26" fill="none" aria-hidden="true">
      <path d="M4 21 L13 3 L22 21 L13 15 Z" fill="#2DCEE6" />
      <path d="M13 3 L13 15" stroke={stroke} strokeWidth="1.6" />
    </svg>
  );
}
