/**
 * Ai spus „ultima dată" și iar nu a fost? Vezi ce arată creierul tău.
 *
 * GENERATED by `scripts/import-brainmap-lps.mjs` from the client's
 * `lp-brainmap-adictie.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift. Only the
 * per-condition ([NIȘAT]) copy lives here — the shared page structure is
 * `components/lp/LpBrainmapTemplate.tsx`.
 */
import type { BrainmapLp } from "@/content/campaign-lps";

export const ADICTII_LP: BrainmapLp = {
  "slug": "adictii",
  "route": "adictii",
  "concern": "adictii",
  "seo": {
    "title": "Ai spus „ultima dată\" și iar nu a fost? Vezi ce arată creierul tău. — Emmanuel CliniX"
  },
  "hero": {
    "titleHtml": "Ai spus „ultima dată\" și <em>iar nu a fost</em>",
    "lede": "Ce se întâmplă în creierul tău în momentul în care nu te poți opri se vede pe o hartă. În 30 de minute vezi cum arată."
  },
  "identificare": {
    "cards": [
      {
        "tag": "Seara",
        "text": "Deschizi telefonul pentru două minute. Ridici ochii și au trecut două ore."
      },
      {
        "tag": "Când e greu",
        "text": "Orice zi proastă se termină la fel. Știai încă de dimineață cum se termină."
      },
      {
        "tag": "A doua zi",
        "text": "Îți promiți din nou. Și ține exact până la primul moment în care ești obosit."
      }
    ],
    "pull": "Trei situații diferite. Aceeași întrebare: de ce știu ce am de făcut și tot nu o fac?"
  },
  "why": {
    "tried": "Aplicații de blocat. Praguri. Pauze de o lună. Pariuri cu tine. Ai șters aplicația de trei ori și ai reinstalat-o de patru.",
    "assumption": "Toate au presupus că e o problemă de voință. Dacă voința ar fi fost de ajuns, se rezolva de prima dată.",
    "cost": "Între timp se adună ce ai pierdut. Ore, bani, seri cu oameni la care ții. Și senzația, tot mai clară, că nu tu decizi.",
    "analogy": "Inima ți-o verifici. Analizele de sânge ți le faci an de an. Creierul — niciodată. Deși acolo se ia decizia pe care nu reușești să o ții."
  },
  "mapSentence": "Vezi ce zone sunt prea active, care sunt prea lente și unde exact cedează frâna, înainte să apuci să te gândești. În cazul tău, nu în general.",
  "qualify": {
    "fits": [
      "Ai încercat de mai multe ori să te oprești singur și nu a ținut",
      "Continui deși vezi clar ce te costă",
      "Reziști câteva zile și apoi revii exact de unde ai plecat"
    ],
    "extraExclusion": "Ai dependență de alcool sau de substanțe cu simptome fizice la întrerupere — atunci ai nevoie întâi de îngrijire medicală de specialitate"
  },
  "faq": [
    {
      "q": "La mine e vorba de telefon și scroll, nu de altceva. Tot se aplică?",
      "a": "Da. Mecanismul din creier e același, indiferent ce e la capătul lui: aceeași buclă de recompensă și același loc în care se ia decizia. Ce diferă e cât te costă. Nu clasificăm oamenii pe pagina asta — măsurăm ce face creierul tău."
    },
    {
      "q": "Rămâne între noi?",
      "a": "Da. Nimic nu iese din clinică. Discuția de la telefon, harta și PDF-ul sunt confidențiale și nu se transmit nimănui. Nu ceri trimitere de la nimeni și nu apare nicăieri."
    }
  ],
  "form": {
    "title": "Vezi ce se întâmplă în creierul tău, în loc să mai promiți încă o dată",
    "situatieLabel": "Despre ce e vorba?",
    "situatieOptions": [
      "Telefon, scroll sau jocuri",
      "Alcool",
      "Altceva pe care nu îl pot opri"
    ],
    "durataLabel": "De cât timp e așa?",
    "incercatPlaceholder": "Pauze, aplicații, terapie, încercări de a te opri… scrie pe scurt. Ne ajută să știm de unde pornim."
  },
  "legal": "BrainMap este un instrument de evaluare inițială și nu constituie diagnostic medical. Dependența de alcool sau de substanțe necesită evaluare și tratament de specialitate; această evaluare nu le înlocuiește. Rezultatele pot varia."
};
