/**
 * Trăiești cu o tensiune care nu se oprește? Află de unde pleacă.
 *
 * GENERATED by `scripts/import-brainmap-lps.mjs` from the client's
 * `lp-brainmap-anxietate.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift. Only the
 * per-condition ([NIȘAT]) copy lives here — the shared page structure is
 * `components/lp/LpBrainmapTemplate.tsx`.
 */
import type { BrainmapLp } from "@/content/campaign-lps";

export const ANXIETATE_LP: BrainmapLp = {
  "slug": "anxietate",
  "route": "anxietate",
  "concern": "anxietate",
  "seo": {
    "title": "Trăiești cu o tensiune care nu se oprește? Află de unde pleacă. — Emmanuel CliniX"
  },
  "hero": {
    "titleHtml": "Trăiești cu o tensiune care <em>nu se oprește niciodată</em>",
    "lede": "Starea în care trăiești se vede pe o hartă a activității creierului tău. În 30 de minute vezi cum arată."
  },
  "identificare": {
    "cards": [
      {
        "tag": "Dimineața",
        "text": "Te trezești cu ghemul în stomac înainte să se întâmple ceva. Ziua nici n-a început."
      },
      {
        "tag": "La birou",
        "text": "Un mail, un telefon, o ședință. Inima o ia razna și trebuie să ieși din încăpere."
      },
      {
        "tag": "Seara",
        "text": "Corpul e obosit, capul derulează tot ce ai zis azi. Și tot ce ar putea urma mâine."
      }
    ],
    "pull": "Trei situații diferite. Aceeași întrebare la toți: de ce tocmai la mine?"
  },
  "why": {
    "tried": "Respirații. Magneziu. Sport. Aplicații de meditație. Poate și o cutie luată la nevoie. Poate a mers o lună. Poate deloc.",
    "assumption": "Toate au fost presupuneri. Soluții generale pentru o problemă care nu e generală.",
    "cost": "Între timp refuzi lucruri. Amâni întâlniri, conduci mai puțin, eviți încăperi pline. Nu pentru că nu vrei, ci pentru că nu știi când te prinde din nou.",
    "analogy": "Inima ți-o verifici. Analizele de sânge ți le faci an de an. Creierul — niciodată. Deși de acolo pleacă tot."
  },
  "mapSentence": "Vezi ce zone sunt prea active, care sunt prea lente și unde exact se rupe echilibrul. În cazul tău, nu în general.",
  "qualify": {
    "fits": [
      "Trăiești cu o stare de alertă care nu se oprește",
      "Ai episoade în care corpul o ia înaintea ta",
      "Eviți situații pe care înainte le făceai fără să te gândești"
    ],
    "extraExclusion": null
  },
  "faq": [
    {
      "q": "Am fost deja la psiholog. Cu ce e diferit?",
      "a": "Nu înlocuiește terapia. Diferența e că pleacă de la o măsurătoare, nu de la ce reușești să povestești într-o ședință. Harta arată ce se întâmplă în creierul tău, iar de acolo discuția devine concretă."
    },
    {
      "q": "Și dacă nu iese nimic pe hartă?",
      "a": "Iese întotdeauna ceva — activitatea creierului nu e niciodată plată. Uneori rezultatul e chiar acesta: excluzi o cauză și știi unde să cauți mai departe. Îți spunem exact ce vedem, fără să adăugăm ceva ca să pară mai mult."
    }
  ],
  "form": {
    "title": "Vezi ce se întâmplă în creierul tău, în loc să mai ghicești",
    "situatieLabel": "Care e situația ta?",
    "situatieOptions": [
      "Stare de alertă permanentă",
      "Episoade în care corpul o ia razna",
      "Evit situații pe care înainte le făceam normal"
    ],
    "durataLabel": "De cât timp te confrunți cu asta?",
    "incercatPlaceholder": "Terapie, medicație, suplimente, sport… scrie pe scurt. Ne ajută să știm de unde pornim."
  },
  "legal": "BrainMap este un instrument de evaluare inițială și nu constituie diagnostic medical. Rezultatele pot varia. Pentru simptome severe, recomandăm consultarea unui medic specialist."
};
