/**
 * Te odihnești și nu te încarci? Vezi ce arată creierul tău.
 *
 * GENERATED by `scripts/import-brainmap-lps.mjs` from the client's
 * `lp-brainmap-burnout.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift. Only the
 * per-condition ([NIȘAT]) copy lives here — the shared page structure is
 * `components/lp/LpBrainmapTemplate.tsx`.
 */
import type { BrainmapLp } from "@/content/campaign-lps";

export const BURNOUT_LP: BrainmapLp = {
  "slug": "burnout",
  "route": "burnout",
  "concern": "burnout",
  "seo": {
    "title": "Te odihnești și nu te încarci? Vezi ce arată creierul tău. — Emmanuel CliniX"
  },
  "hero": {
    "titleHtml": "Nu ești leneș. <em>Ai rămas fără rezervă</em>",
    "lede": "Starea în care ai ajuns se vede pe o hartă a activității creierului tău. În 30 de minute vezi cum arată."
  },
  "identificare": {
    "cards": [
      {
        "tag": "Luni dimineața",
        "text": "Ai avut liber tot weekendul și te trezești la fel de golit ca vineri seara."
      },
      {
        "tag": "La muncă",
        "text": "Citești același paragraf de trei ori. Ce făceai în două ore îți ia acum toată ziua."
      },
      {
        "tag": "Cu oamenii",
        "text": "Nu mai ai răbdare cu nimeni, nici la birou, nici acasă. Și după aia te simți prost pentru asta."
      }
    ],
    "pull": "Trei situații diferite. Aceeași întrebare: de ce nu mă mai încarc, oricât m-aș odihni?"
  },
  "why": {
    "tried": "Concediu. Somn mai mult. Vitamine. Ți-ai luat o săptămână liberă. Te-ai întors și în trei zile erai la fel.",
    "assumption": "Toate au presupus că e o problemă de odihnă. Dacă odihna ar fi fost soluția, ar fi funcționat până acum.",
    "cost": "Între timp lucrurile merg în jos exact când ai nevoie de ele. Termene ratate, decizii amânate, senzația că oricine ar face treaba mai bine decât tine.",
    "analogy": "Inima ți-o verifici. Analizele de sânge ți le faci an de an. Creierul — niciodată. Deși el decide dacă te reîncarci sau nu."
  },
  "mapSentence": "Vezi ce zone sunt prea active, care sunt prea lente și unde exact nu se mai face trecerea din efort în refacere. În cazul tău, nu în general.",
  "qualify": {
    "fits": [
      "Te odihnești și nu te simți odihnit",
      "Munca pe care o făceai ușor îți ia acum de trei ori mai mult",
      "Ai ajuns să nu mai ai răbdare cu oamenii la care ții"
    ],
    "extraExclusion": null
  },
  "faq": [
    {
      "q": "Burnout-ul e o problemă de job. Ce caut la clinică?",
      "a": "Cauza poate fi la job. Ce s-a întâmplat între timp e în creierul tău, și rămâne acolo și după ce schimbi jobul. De asta se întorc oamenii din concediu la fel cum au plecat. Măsurăm exact partea care nu se rezolvă cu o săptămână liberă."
    },
    {
      "q": "Află angajatorul meu ceva?",
      "a": "Nu. Nimic din ce discutăm nu iese din clinică. Harta și PDF-ul sunt ale tale și nu se transmit nimănui, indiferent cine plătește evaluarea."
    }
  ],
  "form": {
    "title": "Vezi ce se întâmplă în creierul tău, în loc să mai împingi de tine",
    "situatieLabel": "Care e situația ta?",
    "situatieOptions": [
      "Mă odihnesc și nu mă încarc",
      "Îmi ia de câteva ori mai mult să fac aceleași lucruri",
      "Nu mai am răbdare cu nimeni"
    ],
    "durataLabel": "De cât timp e așa?",
    "incercatPlaceholder": "Concedii, pauze, terapie, schimbări la job… scrie pe scurt. Ne ajută să știm de unde pornim."
  },
  "legal": "BrainMap este un instrument de evaluare inițială și nu constituie diagnostic medical. Rezultatele pot varia. Pentru simptome severe, recomandăm consultarea unui medic specialist."
};
