/**
 * Nu ești trist, doar nu mai simți nimic? Vezi ce arată creierul tău.
 *
 * GENERATED by `scripts/import-brainmap-lps.mjs` from the client's
 * `lp-brainmap-dispozitie.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift. Only the
 * per-condition ([NIȘAT]) copy lives here — the shared page structure is
 * `components/lp/LpBrainmapTemplate.tsx`.
 */
import type { BrainmapLp } from "@/content/campaign-lps";

export const DISPOZITIE_LP: BrainmapLp = {
  "slug": "dispozitie",
  "route": "dispozitie",
  "concern": "depresie",
  "seo": {
    "title": "Nu ești trist, doar nu mai simți nimic? Vezi ce arată creierul tău. — Emmanuel CliniX"
  },
  "hero": {
    "titleHtml": "Nu ești trist. <em>Nu mai simți nimic</em>",
    "lede": "Ce se întâmplă în creierul tău se vede pe o hartă. În 30 de minute vezi cum arată."
  },
  "identificare": {
    "cards": [
      {
        "tag": "Dimineața",
        "text": "Te trezești și primul gând e cât mai e până seara. Nu s-a întâmplat nimic rău. Pur și simplu nu ai de ce să te ridici."
      },
      {
        "tag": "Peste zi",
        "text": "Muncă, copii, mesaje. Din afară pare că funcționezi normal. Pe dinăuntru nu e nimic."
      },
      {
        "tag": "Lucrurile care-ți plăceau",
        "text": "Sunt tot acolo. Doar că nu mai simți nimic când le faci."
      }
    ],
    "pull": "Trei situații diferite. Aceeași întrebare: de cât timp e așa și de ce nu trece?"
  },
  "why": {
    "tried": "Vacanțe. Sport. Vitamina D. Sfaturi de la oameni care te iubesc. „Ieși mai mult.\" Poate a ținut o săptămână. Poate deloc.",
    "assumption": "Toate au presupus că e o chestiune de voință. Dacă ar fi fost, se rezolva de mult.",
    "cost": "Între timp se strâng lucrurile amânate. Mesaje necitite, invitații refuzate, dimineți în care ai rămas în pat. Fiecare zi la fel o face pe următoarea mai grea.",
    "analogy": "Inima ți-o verifici. Analizele de sânge ți le faci an de an. Creierul — niciodată. Deși el decide cum te simți."
  },
  "mapSentence": "Vezi ce zone sunt prea active, care sunt prea lente și unde exact se pierde echilibrul dintre zonele active și cele lente. În cazul tău, nu în general.",
  "qualify": {
    "fits": [
      "Te simți la fel de mult timp, indiferent ce se întâmplă în jur",
      "Lucrurile care îți plăceau nu îți mai spun nimic",
      "Din afară pare că funcționezi, iar pe dinăuntru nu recunoști nimic"
    ],
    "extraExclusion": "Ai gânduri de a-ți face rău — nu completa formularul, sună la 112 sau mergi la cea mai apropiată unitate de primiri urgențe"
  },
  "faq": [
    {
      "q": "Iau deja medicație prescrisă. Mai are sens?",
      "a": "Da, și nu opri nimic pe cont propriu. Ne spui la telefon ce iei, ca să ținem cont la interpretare. Harta nu înlocuiește tratamentul și nu îl contrazice — arată cum funcționează creierul tău acum, iar asta e informație utilă și pentru medicul care te urmărește."
    },
    {
      "q": "E depresie sau doar o perioadă mai grea?",
      "a": "Diagnosticul îl pune un medic, nu o pagină și nici un aparat singur. BrainMap arată ce face creierul tău în momentul măsurătorii. Dacă vedem lucruri care cer un consult de specialitate, îți spunem direct și te îndrumăm mai departe."
    }
  ],
  "form": {
    "title": "Vezi ce se întâmplă în creierul tău, în loc să mai aștepți să treacă",
    "situatieLabel": "Care e situația ta?",
    "situatieOptions": [
      "Mă simt la fel de mult timp, orice s-ar întâmpla",
      "Nu mai simt nimic la lucrurile care îmi plăceau",
      "Funcționez pe dinafară și atât"
    ],
    "durataLabel": "De cât timp e așa?",
    "incercatPlaceholder": "Terapie, medicație, consulturi anterioare… scrie pe scurt. Ne ajută să știm de unde pornim."
  },
  "legal": "BrainMap este un instrument de evaluare inițială și nu constituie diagnostic medical. Nu înlocuiește consultul psihiatric sau psihologic și nu substituie un tratament prescris. Rezultatele pot varia. Dacă te confrunți cu gânduri de a-ți face rău, sună la 112."
};
