/**
 * Opt ore la birou și o oră de muncă făcută? Vezi ce arată creierul tău.
 *
 * GENERATED by `scripts/import-brainmap-lps.mjs` from the client's
 * `lp-brainmap-focus.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift. Only the
 * per-condition ([NIȘAT]) copy lives here — the shared page structure is
 * `components/lp/LpBrainmapTemplate.tsx`.
 */
import type { BrainmapLp } from "@/content/campaign-lps";

export const FOCUS_LP: BrainmapLp = {
  "slug": "focus",
  "route": "focus",
  "concern": "performanta-cognitiva",
  "seo": {
    "title": "Opt ore la birou și o oră de muncă făcută? Vezi ce arată creierul tău. — Emmanuel CliniX"
  },
  "hero": {
    "titleHtml": "Opt ore la birou, <em>o oră de muncă făcută</em>",
    "lede": "Felul în care creierul tău își ține atenția se vede pe o hartă. În 30 de minute vezi cum arată."
  },
  "identificare": {
    "cards": [
      {
        "tag": "Când te apuci",
        "text": "Deschizi documentul și deschizi și un tab. La al treilea nu mai știi cu ce începuseși."
      },
      {
        "tag": "La ședințe",
        "text": "Auzi tot și nu reții nimic. Recitești notițele și par scrise de altcineva."
      },
      {
        "tag": "Seara",
        "text": "Ai fost ocupat toată ziua. Și nu poți numi un singur lucru terminat."
      }
    ],
    "pull": "Trei situații diferite. Aceeași întrebare: unde se duc orele mele?"
  },
  "why": {
    "tried": "Pomodoro. Notion. Telefonul în alt sertar. Liste refăcute în fiecare duminică. Un curs de productivitate. Poate a ținut o săptămână.",
    "assumption": "Toate au presupus că e o problemă de organizare. Nu poți organiza o atenție care nu stă.",
    "cost": "Între timp compensezi cu ore. Lucrezi seara, lucrezi în weekend, ca să scoți cât scoate altul până la prânz. Și tot rămâi în urmă.",
    "analogy": "Inima ți-o verifici. Analizele de sânge ți le faci an de an. Creierul — niciodată. Deși el decide cât poți ține atenția pe un singur lucru."
  },
  "mapSentence": "Vezi ce zone sunt prea active, care sunt prea lente și unde exact se pierde atenția, la câteva minute după ce te apuci. În cazul tău, nu în general.",
  "qualify": {
    "fits": [
      "Îți ia toată ziua ce făceai înainte în două ore",
      "Citești același paragraf de mai multe ori și nu rămâne nimic",
      "Începi multe lucruri și termini puține"
    ],
    "extraExclusion": null
  },
  "faq": [
    {
      "q": "Nu sunt doar prost organizat?",
      "a": "Poate ești și asta. Diferența se vede la test: dacă metodele de organizare ar fi fost problema, măcar una dintre ele ar fi ținut mai mult de o lună. Harta arată dacă creierul tău reușește să susțină atenția sau dacă o pierde de fiecare dată în același punct."
    },
    {
      "q": "E ADHD?",
      "a": "Diagnosticul îl pune un medic, după o evaluare completă — nu un aparat și nu o pagină. BrainMap arată cum arată activitatea creierului tău acum. Dacă vedem lucruri care cer un consult de specialitate, îți spunem direct și te îndrumăm mai departe."
    }
  ],
  "form": {
    "title": "Vezi unde se pierde atenția ta, în loc să mai încerci o metodă",
    "situatieLabel": "Care e situația ta?",
    "situatieOptions": [
      "Nu mă pot apuca de lucru",
      "Mă apuc și pierd firul în câteva minute",
      "Termin ziua fără să fi terminat nimic"
    ],
    "durataLabel": "De cât timp e așa?",
    "incercatPlaceholder": "Metode de organizare, aplicații, cursuri, consulturi… scrie pe scurt. Ne ajută să știm de unde pornim."
  },
  "legal": "BrainMap este un instrument de evaluare inițială și nu constituie diagnostic medical. Rezultatele pot varia. Pentru simptome severe, recomandăm consultarea unui medic specialist."
};
