/**
 * Migrenele îți iau zile întregi din fiecare lună? Vezi ce arată creierul tău.
 *
 * GENERATED by `scripts/import-brainmap-lps.mjs` from the client's
 * `lp-brainmap-migrene.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift. Only the
 * per-condition ([NIȘAT]) copy lives here — the shared page structure is
 * `components/lp/LpBrainmapTemplate.tsx`.
 */
import type { BrainmapLp } from "@/content/campaign-lps";

export const MIGRENE_LP: BrainmapLp = {
  "slug": "migrene",
  "route": "migrene",
  "concern": "migrene",
  "seo": {
    "title": "Migrenele îți iau zile întregi din fiecare lună? Vezi ce arată creierul tău. — Emmanuel CliniX"
  },
  "hero": {
    "titleHtml": "Migrenele îți iau <em>zile întregi din fiecare lună</em>",
    "lede": "Activitatea creierului tău între crize se vede pe o hartă. În 30 de minute vezi cum arată."
  },
  "identificare": {
    "cards": [
      {
        "tag": "Înainte",
        "text": "Știi că vine cu ore înainte. Lumina devine prea tare, cuvintele se încurcă și nu poți face nimic să o oprești."
      },
      {
        "tag": "În criză",
        "text": "Cameră întunecată, telefon pe silențios, ziua anulată. Uneori și a doua zi."
      },
      {
        "tag": "După",
        "text": "Rămâi golit. Funcționezi la jumătate și aștepți următoarea, fără să știi când vine."
      }
    ],
    "pull": "Trei momente diferite. Aceeași întrebare: de ce atât de des și de ce tocmai la mine?"
  },
  "why": {
    "tried": "Triptani. Magneziu. Jurnal de declanșatori. Ai scos cafeaua, brânza, vinul roșu, ecranele seara. Poate a mers o lună. Poate deloc.",
    "assumption": "Toate au încercat să oprească criza după ce începe, sau să ghicească ce o pornește. Niciuna nu s-a uitat la ce face creierul tău în zilele dintre ele.",
    "cost": "Între timp îți construiești viața în jurul lor. Amâni programări, refuzi ieșiri, ții mereu o cutie în geantă. Nu pentru că vrei, ci pentru că nu știi când urmează.",
    "analogy": "Inima ți-o verifici. Analizele de sânge ți le faci an de an. Creierul — niciodată. Deși de acolo pornește criza."
  },
  "mapSentence": "Vezi ce zone sunt prea active, care sunt prea lente și cum arată activitatea creierului tău între crize. În cazul tău, nu în general.",
  "qualify": {
    "fits": [
      "Ai mai mult de patru zile cu migrenă într-o lună",
      "Ți-ai organizat programul în jurul crizelor",
      "Medicația te ajută în criză, dar frecvența nu scade"
    ],
    "extraExclusion": "Ai dureri de cap apărute brusc, recent sau însoțite de alte simptome neurologice — mergi întâi la medic"
  },
  "faq": [
    {
      "q": "Am fost deja la neurolog. Cu ce e diferit?",
      "a": "Nu înlocuiește consultul neurologic și nu stabilește un diagnostic. Neurologul se ocupă de criză și de tratament. Noi măsurăm cum arată activitatea creierului tău în zilele dintre crize — informație pe care un consult obișnuit nu o produce. Cele două se completează."
    },
    {
      "q": "Pot veni dacă sunt în criză chiar acum?",
      "a": "Nu. Programăm scanarea într-o zi fără criză, altfel măsurătoarea nu spune nimic despre cum funcționezi în restul lunii. Ne spui la telefon cum arată de obicei ciclul tău și găsim o fereastră potrivită."
    }
  ],
  "form": {
    "title": "Vezi ce face creierul tău între crize, nu doar în timpul lor",
    "situatieLabel": "Cum arată migrenele tale?",
    "situatieOptions": [
      "Sub 4 zile pe lună",
      "Între 4 și 10 zile pe lună",
      "Peste 10 zile pe lună"
    ],
    "durataLabel": "De cât timp te confrunți cu ele?",
    "incercatPlaceholder": "Medicație, investigații, jurnal de declanșatori… scrie pe scurt. Ne ajută să știm de unde pornim."
  },
  "legal": "Migrena necesită evaluare neurologică de specialitate. BrainMap este un instrument de evaluare inițială, nu constituie diagnostic medical și nu înlocuiește consultul neurologic. Rezultatele pot varia."
};
