/**
 * Analizele ies bine și atacurile continuă? Vezi ce arată creierul tău.
 *
 * GENERATED by `scripts/import-brainmap-lps.mjs` from the client's
 * `lp-brainmap-atacuri-de-panica.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift. Only the
 * per-condition ([NIȘAT]) copy lives here — the shared page structure is
 * `components/lp/LpBrainmapTemplate.tsx`.
 */
import type { BrainmapLp } from "@/content/campaign-lps";

export const PANICA_LP: BrainmapLp = {
  "slug": "panica",
  "route": "panica",
  "concern": "atacuri-panica",
  "seo": {
    "title": "Analizele ies bine și atacurile continuă? Vezi ce arată creierul tău. — Emmanuel CliniX"
  },
  "hero": {
    "titleHtml": "Corpul o ia razna și <em>nu îl poți opri</em>",
    "lede": "Ce se întâmplă în creierul tău între episoade se vede pe o hartă. În 30 de minute vezi cum arată."
  },
  "identificare": {
    "cards": [
      {
        "tag": "În timpul",
        "text": "Inima bubuie, aerul nu ajunge, mâinile amorțesc. Zece minute care par o oră."
      },
      {
        "tag": "După",
        "text": "Analizele sunt bune. Ți s-a spus că inima e în regulă. Și tot nu înțelegi ce a fost."
      },
      {
        "tag": "Între ele",
        "text": "Nu mai e vorba de episod. E teama că urmează unul într-un loc din care nu poți ieși."
      }
    ],
    "pull": "Trei momente diferite. Aceeași întrebare: dacă totul e în regulă, atunci ce a fost asta?"
  },
  "why": {
    "tried": "EKG. Analize. Holter. Poate și o cutie luată la nevoie. Ți s-a spus de fiecare dată că nu ai nimic. Și se întâmplă mai departe.",
    "assumption": "Toate au căutat unde nu era. Inima ta a fost verificată. Nimeni nu s-a uitat mai sus de ea.",
    "cost": "Între timp îți micșorezi harta. Nu mai conduci pe autostradă, eviți metroul, verifici unde e ieșirea din orice sală. Fiecare loc evitat îl face pe următorul mai greu.",
    "analogy": "Inima ți-ai verificat-o deja, de mai multe ori. Creierul — niciodată. Deși de acolo pornește alarma."
  },
  "mapSentence": "Vezi ce zone sunt prea active, care sunt prea lente și unde exact pornește alarma prea devreme. În cazul tău, nu în general.",
  "qualify": {
    "fits": [
      "Ai avut episoade în care corpul o ia razna fără un motiv clar",
      "Analizele și consultul cardiologic au ieșit bine",
      "Ai început să eviți locuri de teamă că urmează unul"
    ],
    "extraExclusion": "Ai avut primul episod recent și nu ai fost încă la medic — exclude întâi cauzele cardiace"
  },
  "faq": [
    {
      "q": "Am făcut toate analizele și sunt bune. Atunci ce caut aici?",
      "a": "Exact de aceea. Analizele bune spun ce nu e — nu spun ce este. Cardiologul verifică inima, iar când inima e în regulă discuția se oprește acolo. Noi măsurăm activitatea creierului, adică locul din care pornește reacția pe care o simți în corp."
    },
    {
      "q": "Pot face un episod în timpul scanării?",
      "a": "Scanarea e liniștită: stai pe scaun, cu ochii închiși și apoi deschiși, cu cineva lângă tine tot timpul. Dacă te simți inconfortabil, se oprește pe loc și se reia când ești pregătit. Spune-ne la telefon dinainte, ca să știm."
    }
  ],
  "form": {
    "title": "Vezi de unde pornește alarma, în loc să mai ghicești",
    "situatieLabel": "Care e situația ta?",
    "situatieOptions": [
      "Am episoade și nu am fost încă la medic",
      "Am făcut analize și au ieșit bine",
      "Evit locuri de teamă că urmează unul"
    ],
    "durataLabel": "De cât timp se întâmplă?",
    "incercatPlaceholder": "Investigații, consulturi, medicație, terapie… scrie pe scurt. Ne ajută să știm de unde pornim."
  },
  "legal": "BrainMap este un instrument de evaluare inițială și nu constituie diagnostic medical. Simptomele cardiace trebuie evaluate întâi de un medic. Rezultatele pot varia. Pentru simptome severe, recomandăm consultarea unui medic specialist."
};
