/**
 * Ești în priză de dimineața până seara? Află de ce.
 *
 * GENERATED by `scripts/import-brainmap-lps.mjs` from the client's
 * `lp-brainmap-stres.html`. Do not edit by hand: re-run the importer against the
 * client's revised HTML instead, so the two copies can never drift. Only the
 * per-condition ([NIȘAT]) copy lives here — the shared page structure is
 * `components/lp/LpBrainmapTemplate.tsx`.
 */
import type { BrainmapLp } from "@/content/campaign-lps";

export const STRES_LP: BrainmapLp = {
  "slug": "stres",
  "route": "stres",
  "concern": "stres",
  "seo": {
    "title": "Ești în priză de dimineața până seara? Află de ce. — Emmanuel CliniX"
  },
  "hero": {
    "titleHtml": "Corpul tău e în priză <em>de luni de zile</em>",
    "lede": "Starea în care trăiești se vede pe o hartă a activității creierului tău. În 30 de minute vezi cum arată."
  },
  "identificare": {
    "cards": [
      {
        "tag": "Dimineața",
        "text": "Te trezești cu maxilarul încleștat și umerii ridicați. Nu s-a întâmplat încă nimic."
      },
      {
        "tag": "Peste zi",
        "text": "Începi zece lucruri și nu duci niciunul până la capăt. Seara nu poți spune cu ce ai umplut ziua."
      },
      {
        "tag": "Duminica",
        "text": "Ai două zile libere și tot nu reușești să te oprești. Corpul stă, capul lucrează mai departe."
      }
    ],
    "pull": "Trei situații diferite. Aceeași întrebare la toți: de ce nu mă mai pot opri?"
  },
  "why": {
    "tried": "Concedii. Sport. Magneziu. Aplicații de respirație. Ai scos cafeaua de după-amiază. Poate a mers o săptămână. Poate deloc.",
    "assumption": "Toate au fost presupuneri. Soluții generale pentru o problemă care nu e generală.",
    "cost": "Între timp plătești în altă parte. Somnul, răbdarea cu ai tăi, atenția la lucrurile care contau. Se duc pe rând și nu poți spune exact când.",
    "analogy": "Inima ți-o verifici. Analizele de sânge ți le faci an de an. Creierul — niciodată. Deși el decide când ieși din alertă și când nu."
  },
  "mapSentence": "Vezi ce zone sunt prea active, care sunt prea lente și unde exact rămâne creierul blocat în alertă. În cazul tău, nu în general.",
  "qualify": {
    "fits": [
      "Ești în alertă de dimineața până seara, fără pauză",
      "Îți ții umerii, maxilarul sau stomacul încordate fără să vrei",
      "Te odihnești două zile și tot nu reușești să te oprești"
    ],
    "extraExclusion": null
  },
  "faq": [
    {
      "q": "Toată lumea e stresată. La mine chiar e altceva?",
      "a": "Asta e exact ce măsurăm. Stresul normal apare, face ce are de făcut și trece. Când nu mai trece, se vede în activitatea creierului. Harta arată dacă la tine sistemul rămâne pornit sau nu — și nu depinde de cât de rău ți se pare ție."
    },
    {
      "q": "Și dacă iese că sunt în regulă?",
      "a": "Atunci pleci știind asta, negru pe alb, și cauți în altă parte. E un rezultat, nu o vizită pierdută. Îți spunem exact ce vedem, fără să adăugăm ceva ca să pară mai mult."
    }
  ],
  "form": {
    "title": "Vezi ce se întâmplă în creierul tău, în loc să mai ghicești",
    "situatieLabel": "Care e situația ta?",
    "situatieOptions": [
      "Sunt în alertă permanentă",
      "Nu mă pot opri din făcut lucruri",
      "Mă odihnesc și nu mă simt odihnit"
    ],
    "durataLabel": "De cât timp e așa?",
    "incercatPlaceholder": "Concedii, suplimente, sport, terapie… scrie pe scurt. Ne ajută să știm de unde pornim."
  },
  "legal": "BrainMap este un instrument de evaluare inițială și nu constituie diagnostic medical. Rezultatele pot varia. Pentru simptome severe, recomandăm consultarea unui medic specialist."
};
